#!/bin/bash
set -euo pipefail

HERE=$(dirname "$(realpath "${BASH_SOURCE[0]:-$0}")")
LLAMA_ROOT=${LLAMA_ROOT:-/var/run/media/zenobius/Backup/LLMModels}
TEMPLATE="$HERE/models.ini.in"
PRESET="$HERE/models.ini"

python3 - "$TEMPLATE" "$PRESET" "$LLAMA_ROOT" <<'PY'
from pathlib import Path
import sys

template, preset, llama_root = map(Path, sys.argv[1:])
text = template.read_text()
lines = []
for line in text.splitlines():
    if line.lstrip().startswith('; llama-root ='):
        lines.append('; Generated from models.ini.in by llama-router.sh.')
        lines.append('; Do not edit this file by hand.')
    else:
        lines.append(line.replace('{llama-root}', str(llama_root)))
preset.write_text('\n'.join(lines) + '\n')
PY

llama-server \
  --host 0.0.0.0 \
  --port 2000 \
  --models-dir "$LLAMA_ROOT" \
  --models-preset "$PRESET" \
  --models-autoload \
  --models-max 1
