[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.selection]
text = '#e0def4'
background = '#26233a'

[colors.cursor]
text = '#191724'
cursor = '#c4a7e7'

[colors.normal]
black   = '#1f1d2e'
red     = '#ff728c'
green   = '#73e78d'
yellow  = '#ffdb72'
blue    = '#b392db'
magenta = '#4d346a'
cyan    = '#c4a7e7'
white   = '#eae3f2'

[colors.bright]
black   = '#908a96'
red     = '#ff9fb1'
green   = '#a5ffba'
yellow  = '#ffe8a5'
blue    = '#ddc2fe'
magenta = '#e3cdff'
cyan    = '#eddfff'
white   = '#fbf8ff'
