// Word lists that let the engine tell one kind of capitalised text from
// another.
//
// The lists are variety-neutral. Where spellings diverge, both appear.

/**
 * Ordinary English words that turn up in shouted text: "SAVE DATA FIRST",
 * "BACK UP NOW", "WASH HANDS FIRST". A run of capitals made mostly of these is
 * a person raising their voice, not a string of initialisms.
 *
 * 7435 words. Most are distilled offline from 978 local transcripts of
 * English prose: every word written in lower case at least five times, keeping
 * only those written in lower case in at least 92% of their uses, so acronyms
 * cannot enter the list. Code fences and inline code were removed before
 * counting. The remainder is hand-added safety and warning vocabulary, which a
 * technical corpus barely contains.
 *
 * The distillation is why absence means something. The first version of this
 * list held about 400 hand-picked words, so a word missing from it was assumed
 * to be an acronym, and "ROTATE KEYS" was reported as two undefined acronyms.
 *
 * Words that are also common acronyms are removed deliberately, whichever list
 * they came from: CAN, SET, MIX, RAM, PIN, REST, BUS and the rest. Including
 * them would teach the engine to read "CAN RAM SET" as shouting, which is
 * exactly the sequence a technical writer needs flagged.
 */
export const COMMON_WORDS: ReadonlySet<string> = new Set([
  "a", "ab", "abandoned", "abbreviation", "ability", "able", "abort", "aborting", "aborts",
  "about", "above", "abs", "absence", "absent", "absolute", "absolutely", "absorb", "absorbed",
  "absorbs", "abstention", "abstract", "abstraction", "absurd", "ac", "academy", "acc",
  "accent", "accents", "accept", "acceptable", "acceptance", "accepted", "accepting",
  "accepts", "access", "accessibility", "accessible", "accessor", "accessors", "accident",
  "accidentally", "accordingly", "account", "accountant", "accounted", "accounting",
  "accounts", "accrue", "accrues", "acct", "accts", "accumulate", "accumulated", "accumulates",
  "accumulating", "accumulation", "accumulator", "accuracy", "accurate", "accurately",
  "achievable", "achieve", "achieved", "achieves", "acid", "ack", "acknowledge",
  "acknowledged", "acknowledgement", "acks", "acquire", "acronym", "acronyms", "across",
  "acted", "acting", "action", "actionable", "actioned", "actions", "activate", "activates",
  "activation", "active", "actively", "actor", "actors", "acts", "actual", "actually", "ad",
  "adam", "adapt", "adapter", "add", "added", "adding", "addition", "additional",
  "additionally", "additions", "additive", "address", "addressability", "addressed",
  "addresses", "addressing", "adds", "adj", "adjacent", "adjudicate", "adjust", "adjustment",
  "adjustments", "adjusts", "adjvalue", "admin", "admits", "adopt", "adopted", "adopting",
  "adoption", "advance", "advanced", "advances", "advancing", "advantage", "adversarial",
  "adversarially", "adversaries", "adversary", "advertised", "advisor", "advisory", "aerial",
  "aesthetic", "af", "affect", "affected", "affecting", "affects", "affordable", "affordance",
  "affordances", "after", "afternoon", "afterward", "afterwards", "ag", "again", "against",
  "age", "aged", "ageing", "agency", "agent", "agents", "ages", "agg", "aggregate",
  "aggregated", "aggregates", "aggregation", "aggressive", "aggressively", "aging", "agnostic",
  "ago", "agree", "agreed", "agreeing", "agreement", "agrees", "agy", "ahead", "aids", "aim",
  "aimed", "alarm", "alarming", "alert", "algorithm", "alias", "aliases", "align", "aligned",
  "aligning", "alignment", "aligns", "alike", "ality", "alive", "all", "alloc", "allocatable",
  "allocate", "allocated", "allocates", "allocating", "allocation", "allocations", "allocs",
  "allocsum", "allow", "allowance", "allowed", "allowing", "allowlist", "allowlisted",
  "allows", "almanac", "almost", "alone", "along", "alongside", "alpha", "alphabetically",
  "already", "alreadypostedch", "also", "alter", "altered", "alternative", "alternatively",
  "alternatives", "alters", "although", "always", "amber", "ambient", "ambiguity", "ambiguous",
  "amend", "amended", "amending", "amendment", "american", "among", "amount", "amounts",
  "amplifies", "amt", "amts", "an", "analog", "analogous", "analyse", "analysis", "analytic",
  "analyze", "ancestor", "ancestors", "anchor", "anchored", "anchoring", "anchors", "and",
  "android", "aneurin", "angle", "animate", "animation", "animations", "anna", "annotated",
  "annotation", "announced", "announcement", "announcements", "annual", "anomalies", "anomaly",
  "another", "answer", "answerable", "answered", "answering", "answers", "anticipated",
  "antigravity", "any", "anyone", "anything", "anyway", "anywhere", "apart", "apis", "app",
  "apparent", "appear", "appearance", "appeared", "appearing", "appears", "append", "appended",
  "appending", "appends", "applicable", "applicant", "applicants", "application",
  "applications", "applied", "applies", "apply", "applydoc", "applying", "appointed",
  "approach", "approaches", "appropriate", "appropriately", "approval", "approvals", "approve",
  "approved", "approx", "approximate", "approximation", "apps", "apr", "april", "arance",
  "arbiter", "arbitrary", "arc", "architectural", "architecture", "archival", "archive",
  "archived", "archives", "ard", "are", "area", "areas", "arg", "args", "arguably", "argue",
  "argued", "argues", "arguing", "argument", "argv", "arise", "arithmetic", "arity", "armed",
  "arming", "arms", "army", "around", "arrangement", "array", "arraybuffer", "arrays",
  "arrival", "arrive", "arrived", "arrives", "arriving", "arrow", "art", "artefact",
  "artefacts", "articles", "artifact", "artifacts", "as", "ascending", "ashvale", "aside",
  "ask", "asked", "asking", "asks", "asof", "assemble", "assembled", "assembles", "assembling",
  "assembly", "assert", "asserted", "asserting", "assertion", "assertions", "asserts",
  "assess", "assessed", "assessing", "assessment", "asset", "assets", "assign", "assigned",
  "assigning", "assignment", "assignments", "assigns", "assist", "assistant", "assume",
  "assumed", "assumes", "assuming", "assumption", "assumptions", "asymmetric", "asymmetry",
  "async", "at", "ate", "ated", "ation", "ative", "atmosphere", "atomic", "atomically",
  "atomicity", "attach", "attached", "attaches", "attack", "attacked", "attacking", "attacks",
  "attempt", "attempted", "attempting", "attempts", "attendance", "attention", "attest",
  "attestable", "attestation", "attested", "attesting", "attributable", "attribute",
  "attributed", "attributes", "attributing", "attribution", "attrs", "audience", "audio",
  "audit", "audited", "auditing", "auditor", "audits", "aug", "august", "authenticated",
  "authenticode", "author", "authorable", "authored", "authoring", "authorisation",
  "authorised", "authoritative", "authorities", "authority", "authorized", "authors", "auto",
  "automate", "automated", "automatic", "automatically", "automation", "autonomous",
  "autosave", "availability", "available", "average", "averaged", "averages", "averaging",
  "avgchip", "avoid", "avoided", "avoiding", "avoids", "aw", "await", "awaited", "awaiting",
  "awaits", "aware", "away", "awkward", "axes", "ba", "babysitting", "back", "backdated",
  "backdrop", "backed", "backend", "backfill", "background", "backgrounded", "backing",
  "backlog", "backoff", "backroom", "backs", "backslashes", "backstop", "backtick",
  "backticks", "backup", "backups", "backward", "backwards", "bad", "badge", "badges", "badly",
  "bag", "bags", "bake", "baked", "bakes", "baking", "bal", "balance", "balanced", "balances",
  "balancing", "ball", "balof", "ban", "band", "banded", "bands", "bandsfromcuts", "bank",
  "banked", "banned", "banner", "banners", "bans", "bar", "bare", "barely", "bars", "base",
  "based", "baseline", "baselined", "baselines", "bash", "basic", "basis", "batch", "batched",
  "batches", "batching", "batteries", "battery", "bb", "bd", "be", "bears", "beat", "beater",
  "beaters", "beats", "beautifully", "became", "because", "become", "becomes", "becoming",
  "bed", "been", "before", "began", "begin", "begins", "behalf", "behave", "behaves",
  "behaving", "behavior", "behaviour", "behavioural", "behaviourally", "behaviours", "behind",
  "being", "believe", "believed", "believing", "belong", "belonging", "belongs", "below",
  "bench", "benchmark", "beneath", "benefit", "benefits", "benign", "beside", "bespoke",
  "best", "bet", "better", "between", "bevan", "beware", "beyond", "bg", "bias", "bid",
  "bidding", "bids", "bidx", "big", "bigger", "biggest", "billed", "billing", "bills", "bin",
  "binaries", "binary", "bind", "binder", "binding", "bindings", "binds", "bisect", "bit",
  "bite", "bites", "biting", "bits", "bitten", "black", "blackout", "blaenau", "blank",
  "blanket", "blanks", "blast", "ble", "bless", "blessed", "blew", "blind", "blindly", "bloat",
  "blob", "blobs", "block", "blocked", "blocker", "blockers", "blocking", "blockquote",
  "blockquotes", "blocks", "blog", "bludger", "blue", "blueprint", "blunt", "blurb", "board",
  "boards", "body", "bogus", "bold", "bolded", "bolted", "bonus", "book", "booked", "booking",
  "bookkeeping", "books", "bool", "boolean", "boot", "booted", "booth", "booting", "boots",
  "bootstrapper", "border", "borderline", "borders", "born", "both", "bottleneck", "bottom",
  "bought", "bound", "boundaries", "boundary", "bounded", "bounding", "bounds", "box", "boxes",
  "brace", "braces", "brackenford", "bracket", "brackets", "brain", "branch", "branched",
  "branches", "branching", "branchkey", "brand", "brave", "breach", "breadth", "break",
  "breakage", "breakdown", "breaking", "breaks", "breath", "bridge", "bridgend", "brief",
  "briefed", "briefing", "briefly", "briefs", "bring", "bringing", "brings", "british",
  "brittle", "broad", "broadcast", "broaden", "broader", "broadly", "broke", "broken", "broom",
  "broomsquires", "browsable", "browser", "browsers", "browsing", "btn", "bubble", "bucket",
  "bucketed", "bucketing", "buckets", "budget", "budgets", "buffer", "buffered", "buffering",
  "buffers", "bug", "buggy", "bugs", "build", "buildable", "builder", "builders", "building",
  "builds", "buildunits", "built", "builtin", "bulk", "bullet", "bulleted", "bullets", "bump",
  "bumped", "bumping", "bumps", "bun", "bundle", "bundled", "bundler", "bundles", "bundling",
  "buried", "burn", "burned", "burning", "burns", "burst", "bury", "business", "bust", "busy",
  "but", "button", "buttons", "buy", "buying", "buys", "bwthyn", "by", "byline", "bypass",
  "bypassed", "bypasses", "bypassing", "byte", "bytecode", "bytes", "cache", "cached",
  "caches", "caching", "cad", "cadence", "cadences", "cal", "calendar", "calibrate",
  "calibrated", "calibrates", "calibration", "call", "callback", "callbacks", "called",
  "caller", "callers", "calling", "calls", "came", "canary", "cancel", "cancellation",
  "cancellations", "cancelled", "cancels", "candid", "candidate", "candidates", "cannot",
  "canon", "canonical", "canonicalisatio", "canonicalise", "cap", "capabilities", "capability",
  "capable", "capacity", "capitalised", "capped", "capping", "caps", "caption", "capture",
  "captured", "captures", "capturing", "card", "cardref", "cards", "care", "career", "careers",
  "careful", "carefully", "careless", "carelessly", "carer", "caret", "caretaker", "cargo",
  "carmarthenshire", "carousel", "carried", "carries", "carry", "carrying", "cartrefi",
  "cascade", "case", "cases", "cash", "cashpost", "cast", "casts", "catalog", "catch",
  "catches", "catching", "categories", "categorise", "categorised", "category", "caught",
  "cause", "caused", "causes", "causing", "caution", "caveat", "caveats", "ccbody", "ccstate",
  "ce", "ced", "ceiling", "cell", "cells", "census", "central", "centre", "centred",
  "ceremony", "cert", "certain", "certainly", "certainty", "certificate", "certification",
  "certs", "ch", "chain", "chained", "chaining", "chains", "challenge", "champion",
  "champions", "championship", "chance", "chances", "change", "changed", "changes", "changing",
  "channel", "channels", "chant", "char", "character", "characterise", "characterised",
  "characters", "charge", "charges", "chars", "charter", "chase", "chased", "chaser",
  "chasing", "chat", "chatgpt", "cheap", "cheaper", "cheapest", "cheaply", "check",
  "checkable", "checkbox", "checkboxes", "checked", "checker", "checking", "checklist",
  "checkout", "checkouts", "checkpoint", "checkpoints", "checks", "chemical", "cheque",
  "cheques", "cheshire", "child", "children", "chip", "chips", "choice", "choices", "choose",
  "chooses", "choosing", "chose", "chosen", "christmas", "chrome", "chromium", "chronological",
  "chunk", "chunked", "chunking", "chunkref", "chunks", "churn", "churning", "churns", "cids",
  "circular", "citation", "citations", "cite", "cited", "cites", "citing", "city", "claim",
  "claimed", "claiming", "claims", "clamp", "clamped", "clamps", "clarification", "clarify",
  "clarifying", "clarity", "clash", "clashing", "class", "classes", "classic", "classified",
  "classifier", "classifies", "classify", "classifying", "claudecode", "clause", "clauses",
  "clean", "cleaned", "cleaner", "cleanest", "cleaning", "cleanly", "cleanup", "clear",
  "clearance", "cleared", "clearer", "clearest", "clearing", "clearly", "clears", "click",
  "clickable", "clicked", "clicking", "clicks", "client", "clients", "clipboard", "clipped",
  "clipping", "clippy", "clis", "cloak", "clobber", "clobbering", "clock", "clocks", "clone",
  "cloned", "clones", "cloning", "close", "closed", "closely", "closeness", "closer", "closes",
  "closest", "closing", "closure", "closures", "clothing", "cloud", "club", "clubpage",
  "clubpicker", "clubs", "clue", "cluster", "clusters", "clutter", "cmp", "cnclaim", "co",
  "coach", "coarse", "cockpit", "code", "codebase", "coded", "codegen", "codes", "codex",
  "codified", "coding", "coexist", "cognitive", "coherence", "coherent", "coherently",
  "cohort", "cohorts", "coincidence", "col", "cold", "collapse", "collapsed", "collapses",
  "collapsible", "collapsing", "collation", "colleagues", "collect", "collected", "collecting",
  "collection", "collections", "collector", "collects", "collide", "collides", "colliding",
  "collision", "collisions", "colon", "color", "colour", "coloured", "colours", "cols",
  "colspan", "column", "columnar", "columns", "com", "combination", "combinations", "combine",
  "combined", "come", "comes", "comfortable", "comfortably", "coming", "comma", "command",
  "commanded", "commands", "comment", "commentary", "commentaryfacts", "commentator",
  "commentators", "commented", "comments", "commercial", "commission", "commissioned",
  "commit", "commitment", "commits", "committed", "committee", "committing", "common",
  "commonmark", "comms", "communication", "community", "comp", "compact", "compacted",
  "compaction", "companies", "companion", "company", "companyid", "companyids", "comparable",
  "comparator", "compare", "compared", "compares", "comparing", "comparison", "comparisons",
  "compat", "compatibility", "compatible", "compendium", "compensating", "compensation",
  "competing", "competition", "competitions", "competitor", "compilation", "compile",
  "compiled", "compiler", "compiles", "compiling", "complaint", "complete", "completed",
  "completely", "completeness", "completes", "completing", "completion", "complex",
  "complexity", "compliance", "compliant", "comply", "component", "components", "compose",
  "composed", "composer", "composes", "composing", "composite", "composition", "compound",
  "compounding", "comprehension", "comprehensive", "compress", "compressed", "compresses",
  "compression", "compromise", "comps", "computation", "compute", "computed",
  "computelivearea", "computes", "computing", "concat", "concatenate", "concatenated",
  "concatenates", "concatenation", "concats", "conceded", "concedes", "conceding",
  "concentrated", "concept", "conceptual", "concern", "concerns", "concise", "concisely",
  "conclude", "concluded", "concluding", "conclusion", "conclusions", "conclusive", "concrete",
  "concretely", "concurrency", "concurrent", "concurrently", "condition", "conditional",
  "conditionally", "conditions", "confidence", "confident", "confidently", "config",
  "configurable", "configuration", "configure", "configured", "confined", "confirm",
  "confirmation", "confirmations", "confirmcheck", "confirmed", "confirming", "confirms",
  "conflate", "conflated", "conflates", "conflict", "conflicted", "conflicts", "conformance",
  "confused", "confusing", "confusion", "connect", "connected", "connection", "connective",
  "connector", "connectors", "connects", "consecutive", "consent", "consequence",
  "consequences", "consequential", "conservation", "conservative", "consider", "considerably",
  "considered", "consistency", "consistent", "consistently", "console", "consolidate",
  "consolidating", "consolidation", "const", "constant", "constantly", "constants",
  "constraint", "constraints", "construct", "constructed", "constructing", "construction",
  "constructor", "constructors", "constructs", "consts", "consult", "consultant", "consulted",
  "consulting", "consults", "consume", "consumed", "consumer", "consumers", "consumes",
  "consuming", "consumption", "contact", "contacted", "contacts", "contain", "contained",
  "container", "containers", "containing", "containment", "contains", "content", "contention",
  "contents", "contest", "contested", "contests", "context", "contextof", "contexts",
  "contextual", "contiguous", "continental", "continentals", "continuation", "continuations",
  "continue", "continues", "continuing", "continuity", "continuous", "continuously", "contra",
  "contract", "contraction", "contracts", "contradict", "contradicted", "contradicting",
  "contradiction", "contradicts", "contrast", "contrastive", "contribute", "contributed",
  "contributes", "contribution", "contributor", "control", "controlaccount", "controlled",
  "controller", "controllers", "controls", "convenience", "convenient", "convention",
  "conventional", "conventions", "converge", "converged", "converges", "converging",
  "conversation", "conversational", "conversations", "conversion", "conversions", "convert",
  "converted", "converting", "converts", "coordinate", "coordinated", "coordinating",
  "coordination", "coordinator", "copied", "copies", "copilot", "copy", "copyable", "copying",
  "core", "cores", "coreutils", "corner", "corners", "corpus", "correct", "corrected",
  "correcting", "correction", "corrections", "correctly", "correctness", "corrects",
  "correlate", "correlation", "correspondence", "correspondent", "corresponding",
  "corresponds", "corroborated", "corroborating", "corroboration", "corrupt", "corrupted",
  "corrupting", "corruption", "cosmetic", "cost", "costing", "costs", "could", "councils",
  "count", "counted", "counter", "counterexample", "counterpart", "counters", "counting",
  "counts", "couple", "coupled", "coupling", "cover", "coverage", "covered", "covering",
  "covers", "cp", "cracked", "craft", "crash", "crashed", "crashes", "crashing", "crate",
  "crates", "create", "created", "creates", "creating", "creation", "creator", "credential",
  "credentials", "credible", "credit", "credited", "crediting", "credits", "creep", "criteria",
  "criterion", "critical", "critically", "critique", "cron", "cross", "crossed", "crosses",
  "crowd", "crowned", "crucial", "crucially", "crux", "crystal", "cs", "csvs", "ct", "ctx",
  "cull", "culprit", "culprits", "culture", "cumulative", "cup", "cups", "curated", "cure",
  "curl", "currency", "current", "currently", "cursor", "custody", "custom", "customer",
  "customers", "customisation", "cut", "cutoff", "cutoffs", "cutover", "cuts", "cutting",
  "cwd", "cwtch", "cycle", "cycles", "daemon", "daily", "damage", "damaged", "damping",
  "danger", "dangerous", "dangling", "dark", "dash", "dashboard", "dashboards", "dashes",
  "data", "database", "databases", "dataset", "datasets", "date", "dated", "dates", "dating",
  "datum", "day", "days", "dead", "deadline", "deadlock", "deal", "deals", "death", "debit",
  "debits", "debounce", "debounced", "debt", "debtor", "debtors", "debug", "dec", "decay",
  "december", "decide", "decided", "decider", "decides", "deciding", "decimal", "decision",
  "decisions", "decisive", "decisively", "declaration", "declarations", "declarative",
  "declare", "declared", "declares", "declaring", "decline", "declined", "declines", "decode",
  "decoded", "decodes", "decoding", "decompose", "decomposed", "decomposition",
  "decompression", "decompressionst", "decoration", "decorative", "decoupled", "ded", "dedup",
  "dedupe", "deduped", "dedupes", "deep", "deepening", "deeper", "deepest", "deeply", "def",
  "default", "defaulted", "defaulting", "defaults", "defeated", "defeating", "defeats",
  "defect", "defective", "defects", "defence", "defend", "defended", "defender", "defensible",
  "defensive", "defensively", "defer", "deferral", "deferrals", "deferred", "deferring",
  "defers", "deficit", "define", "defined", "defines", "defining", "definitely", "definition",
  "definitions", "definitive", "definitively", "deflate", "deflected", "defs", "degradation",
  "degrades", "degrading", "dek", "delay", "delays", "delegate", "delegated", "delegates",
  "delegating", "delegation", "delete", "deleted", "deletes", "deleting", "deletion",
  "deletions", "deliberate", "deliberately", "delimiter", "deliver", "deliverable",
  "deliverables", "delivered", "delivers", "delivery", "delta", "deltas", "demand", "demanded",
  "demands", "demo", "demonstrably", "demonstrate", "demonstrated", "demonstrates",
  "demonstration", "demoted", "denial", "denied", "denies", "denominator", "dense", "density",
  "dent", "deny", "denylist", "depend", "dependencies", "dependency", "dependent", "depending",
  "depends", "deployed", "deprecated", "deps", "depth", "derby", "deregistered", "derivable",
  "derivation", "derivations", "derive", "derived", "derives", "deriving", "desc",
  "descending", "describe", "described", "describemove", "describes", "describing",
  "description", "descriptions", "descriptive", "descriptor", "deserve", "deserves", "design",
  "designed", "designers", "designing", "designs", "desired", "desk", "desktop", "despite",
  "destination", "destroy", "destroyed", "destroys", "destructive", "destructure", "desync",
  "detached", "detail", "detailed", "detect", "detectable", "detected", "detection",
  "detector", "detectors", "detects", "determine", "determined", "determines", "determinism",
  "deterministic", "deterministical", "dev", "developer", "development", "develops",
  "deviation", "deviations", "device", "devices", "diag", "diagnose", "diagnosed",
  "diagnosing", "diagnosis", "diagnostic", "diagnostics", "diagram", "diagrams", "dial",
  "dialog", "dialogs", "dials", "diary", "dict", "dicts", "did", "die", "died", "dies", "diff",
  "diffed", "differ", "differed", "difference", "differences", "different", "differential",
  "differently", "differing", "difficult", "diffing", "diffs", "dig", "digest", "digit",
  "digits", "dilutes", "dim", "dimension", "dimensions", "dimmed", "ding", "dir", "direct",
  "directed", "direction", "directions", "directive", "directly", "director", "directories",
  "directory", "dirs", "dirty", "disable", "disabled", "disables", "disabling", "disagree",
  "disagreed", "disagreement", "disagrees", "disappear", "disappears", "discard", "discarded",
  "discarding", "discards", "discipline", "disclaimer", "disclose", "disclosed", "discloses",
  "disclosure", "disconnect", "disconnected", "discoverable", "discovered", "discovering",
  "discovers", "discovery", "discrepancy", "discrete", "discriminates", "discriminating",
  "discriminator", "discussed", "discussion", "discussions", "disguised", "disjoint", "disk",
  "dismissal", "dismissed", "dispatch", "dispatched", "dispatcher", "dispatches",
  "dispatching", "display", "displayed", "displaying", "displays", "disposable", "dissolves",
  "dist", "distance", "distinct", "distinction", "distinctive", "distinguish",
  "distinguishable", "distinguished", "distinguishes", "distinguishing", "distort",
  "distortion", "distributed", "distribution", "distributional", "distributions", "distrust",
  "disturb", "disturbed", "disturbing", "div", "diverge", "diverged", "divergence",
  "divergences", "divergent", "diverges", "divide", "divider", "division", "divisions", "divs",
  "dlum", "do", "doable", "doc", "docs", "docstring", "docstrings", "doctor", "document",
  "documentation", "documented", "documenting", "documents", "dodge", "does", "dogfood",
  "dogfooding", "doing", "domain", "domains", "domestic", "dominance", "dominant", "dominate",
  "dominated", "dominates", "donation", "done", "door", "doorway", "dormancy", "dormant",
  "dossier", "dot", "dots", "double", "doubled", "doubles", "doublets", "doubly", "down",
  "downgrade", "downgraded", "downgrades", "download", "downloaded", "downloads", "downstream",
  "dozen", "dozens", "dpd", "draft", "draftbeatsof", "drafted", "drafter", "drafting",
  "drafts", "drag", "drags", "drama", "draw", "drawdown", "drawdowns", "drawer", "drawing",
  "draws", "dress", "dressed", "dressing", "drew", "dribble", "drift", "drifting", "drifts",
  "drill", "drilldown", "drills", "drive", "driven", "driver", "drivers", "drives", "driving",
  "drop", "dropdown", "dropdowns", "dropped", "dropping", "drops", "drought", "drove", "dry",
  "dual", "due", "duel", "duels", "duff", "dugout", "dumb", "dump", "dumped", "dumping",
  "dumps", "dup", "duplicate", "duplicated", "duplicates", "duplicating", "duplication",
  "durability", "durable", "duration", "during", "dust", "duty", "dynamically", "each",
  "eagerly", "ear", "earlier", "earliest", "early", "earn", "earned", "earning", "earns",
  "easier", "easiest", "easily", "eastonleigh", "easy", "eats", "echo", "echoes", "eck",
  "economic", "economy", "ed", "edge", "edges", "edit", "editable", "edited", "editing",
  "edition", "editor", "edits", "edmund", "edu", "education", "effect", "effective",
  "effectively", "effects", "efficiently", "effort", "eight", "either", "elapsed", "electric",
  "element", "elements", "elevation", "eleven", "eligible", "eliminate", "eliminated",
  "elision", "else", "elsewhere", "em", "email", "emailbody", "embed", "embedded", "embedding",
  "embeddings", "embeds", "emergency", "emerging", "emission", "emit", "emits", "emitted",
  "emitting", "empirical", "empirically", "emptied", "empties", "emptiness", "empty", "en",
  "enable", "enabled", "enables", "enabling", "enclosing", "encode", "encoded", "encodes",
  "encoding", "end", "ended", "endgame", "ending", "endings", "endpoint", "ends", "enforce",
  "enforced", "enforcement", "enforces", "enforcing", "engaged", "engagement", "engine",
  "engineering", "engines", "england", "english", "enhance", "enough", "enriched",
  "enrichment", "ensure", "ent", "enter", "entered", "entering", "enters", "entire",
  "entirely", "entities", "entity", "entityid", "entries", "entry", "enum", "enumerate",
  "enumerated", "enumerates", "enumerating", "enumeration", "enums", "env", "envelope",
  "environment", "environmental", "ep", "ephemeral", "epic", "epilog", "epithets", "epoch",
  "equal", "equality", "equally", "equals", "equipment", "equivalence", "equivalent",
  "equivalents", "er", "era", "err", "error", "errored", "erroring", "errors", "ers",
  "escalation", "escape", "escaped", "escapes", "escaping", "especially", "ess", "essential",
  "essentially", "establish", "established", "establishing", "establishment", "estate",
  "estimate", "estimated", "etc", "europe", "european", "evaluate", "evaluated", "evaluates",
  "evaluating", "evaluation", "even", "evening", "event", "events", "eventual", "eventually",
  "ever", "every", "everyone", "everything", "everywhere", "eviction", "evidence", "evidenced",
  "evidently", "evolved", "exact", "exactly", "examine", "examined", "examining", "example",
  "examples", "exceed", "exceeded", "exceeds", "excel", "excellent", "except", "exception",
  "exceptional", "exceptions", "excerpt", "excess", "exchange", "excl", "exclude", "excluded",
  "excludes", "excluding", "exclusion", "exclusions", "exclusive", "exclusively", "excvat",
  "exe", "executable", "execute", "executed", "executes", "executing", "execution", "exemplar",
  "exempt", "exemption", "exemptions", "exempts", "exercise", "exercised", "exercises",
  "exercising", "exhale", "exhausted", "exhaustion", "exhaustive", "exhaustively", "exist",
  "existed", "existence", "existing", "exists", "exit", "exited", "exiting", "exits", "expand",
  "expandable", "expanded", "expander", "expanding", "expands", "expansion", "expect",
  "expectation", "expectations", "expected", "expecting", "expects", "expensive", "experience",
  "experiment", "expert", "expired", "expires", "expiring", "expiry", "explain", "explained",
  "explaining", "explains", "explanation", "explanations", "explanatory", "explicit",
  "explicitly", "exploration", "explore", "explorer", "exploring", "exponential", "export",
  "exported", "exporter", "exports", "expose", "exposed", "exposes", "exposing", "exposure",
  "express", "expressed", "expressible", "expression", "expressions", "extend", "extended",
  "extending", "extends", "extension", "extensions", "external", "externalization",
  "externally", "extra", "extract", "extractable", "extracted", "extracting", "extraction",
  "extractor", "extracts", "extras", "eye", "eyeball", "eyebrow", "eyes", "fable", "fabricate",
  "fabricated", "fabricates", "face", "facet", "facets", "facilities", "facility", "fact",
  "factor", "factored", "factors", "factory", "facts", "factual", "factuality", "factually",
  "fail", "failed", "failing", "fails", "failure", "failures", "fair", "fairly", "faithful",
  "faithfully", "fake", "fall", "fallback", "fallbacks", "fallen", "falling", "falls", "false",
  "falsely", "falsy", "familiarity", "families", "family", "fan", "fans", "faqs", "far",
  "fast", "faster", "fat", "fatigue", "fault", "faults", "favour", "favourite", "fc", "feared",
  "feasibility", "feasible", "feature", "features", "feb", "february", "fed", "federation",
  "fee", "feed", "feedback", "feeding", "feedlines", "feeds", "feel", "feels", "fees", "fell",
  "felt", "fence", "fenced", "fences", "fetch", "fetched", "fetches", "fetching", "few",
  "fewer", "fic", "fiction", "fictional", "fidelity", "field", "fields", "fifteen", "fifth",
  "fight", "fighting", "figure", "figures", "file", "filed", "filename", "filenames", "files",
  "filestore", "filesystem", "filing", "fill", "filled", "filler", "filling", "fills",
  "filter", "filteraccts", "filtered", "filtering", "filters", "final", "finalise",
  "finalising", "finalize", "finalized", "finalizing", "finally", "finals", "finance",
  "finances", "financial", "find", "findability", "finders", "finding", "findings", "finds",
  "fine", "finer", "fingerprint", "fingerprints", "finish", "finished", "finishes",
  "finishing", "fire", "fired", "firefox", "fires", "firewall", "firing", "firm", "first",
  "firsthand", "fiscal", "fit", "fitness", "fits", "fitted", "fitting", "five", "fix",
  "fixable", "fixed", "fixes", "fixing", "fixture", "fixtures", "flag", "flagged", "flagging",
  "flags", "flagship", "flake", "flaky", "flame", "flank", "flash", "flat", "flatly",
  "flatten", "flattened", "flattens", "flattery", "flavour", "flaw", "flesch", "flight",
  "flintshire", "flip", "flipped", "flipping", "flips", "float", "floats", "floor", "floored",
  "flooring", "floors", "flourish", "flow", "flowing", "flows", "flush", "fn", "fns", "focus",
  "focused", "focusing", "fold", "folded", "folder", "folders", "folding", "folds", "follow",
  "followed", "following", "follows", "font", "fonts", "foot", "football", "footballer",
  "footer", "footers", "footgun", "footprint", "for", "forbidden", "forbids", "force",
  "forced", "forces", "forcing", "foreground", "foreign", "forever", "forfeits", "forgery",
  "forget", "forgetting", "forgotten", "fork", "forks", "form", "formalise", "formality",
  "formally", "formant", "format", "formation", "formations", "formats", "formatted",
  "formatter", "formatting", "forming", "forms", "formula", "formulas", "fortnight", "forty",
  "forward", "forwarding", "forwards", "foul", "fouls", "found", "foundation", "foundational",
  "four", "fourteen", "fourth", "fraction", "fractional", "fragile", "fragility", "fragment",
  "fragmented", "fragments", "frame", "framed", "frames", "framework", "framing", "free",
  "freed", "freely", "frees", "freeze", "freezes", "freezing", "french", "frequency",
  "frequent", "frequently", "fresh", "fresher", "freshest", "freshly", "freshness", "fri",
  "friction", "friendly", "from", "front", "frontier", "frontmatter", "fronts", "frozen",
  "full", "fuller", "fully", "fun", "function", "functional", "functionally", "functions",
  "fundamental", "fundamentally", "funder", "funds", "funnels", "furniture", "further",
  "furthest", "future", "fuzz", "fuzzy", "gain", "gained", "gains", "gallery", "game", "games",
  "gap", "gaps", "garbage", "garet", "gareth", "gas", "gate", "gated", "gates", "gather",
  "gathered", "gathering", "gating", "gauge", "gave", "gazmagik", "ge", "gemma", "gen",
  "gender", "general", "generalised", "generalises", "generalising", "generally", "generate",
  "generated", "generates", "generating", "generation", "generator", "generic", "generically",
  "generous", "genre", "gentle", "gentler", "genuine", "genuinely", "geographic", "geometry",
  "german", "gesture", "get", "gets", "getting", "ghost", "giant", "gib", "gibbs", "gigabytes",
  "git", "github", "gitignore", "gitignored", "give", "given", "gives", "giving", "glad",
  "glamorgan", "glance", "glitch", "glob", "global", "globally", "globals", "globs", "glove",
  "gloves", "glue", "glyph", "go", "goal", "goalkeeper", "goalless", "goals", "goes", "going",
  "golden", "goldens", "gone", "good", "google", "got", "gotcha", "gotchas", "goto",
  "governing", "governs", "grab", "grabbed", "grabs", "graceful", "gracefully", "grade",
  "grades", "grading", "graft", "grafted", "grafts", "grain", "grains", "grammar", "grand",
  "grant", "granted", "grants", "granularity", "graph", "great", "greater", "greedy",
  "greenfield", "greens", "grep", "grepped", "grepping", "greps", "grew", "grey", "grid",
  "grinding", "grinds", "gross", "ground", "grounded", "grounding", "grounds", "group",
  "grouped", "grouping", "groups", "grow", "growing", "grown", "grows", "growth", "guarantee",
  "guaranteed", "guaranteeing", "guarantees", "guard", "guarded", "guarding", "guards",
  "guess", "guessed", "guesses", "guessing", "guesswork", "guidance", "guidant", "guide",
  "guides", "gun", "gutted", "gwent", "gz", "gzip", "gzipped", "habit", "had", "half",
  "hallucination", "halves", "hand", "handed", "handful", "handing", "handle", "handled",
  "handler", "handlers", "handles", "handling", "handoff", "handover", "handovers", "hands",
  "hang", "hanging", "hangs", "happen", "happened", "happening", "happens", "happily", "happy",
  "hard", "hardcode", "hardcoded", "hardcodes", "hardcoding", "harden", "hardened",
  "hardening", "harder", "hardest", "hardware", "harm", "harmful", "harmless", "harness",
  "harnesses", "harvests", "has", "hash", "hashed", "hashes", "hatch", "have", "having",
  "hazard", "hazards", "he", "head", "headed", "header", "headerless", "headers", "heading",
  "headings", "headless", "headlessly", "headline", "headroom", "heads", "heals", "health",
  "healthy", "heap", "hear", "heart", "heat", "heathcote", "heavier", "heaviest", "heavily",
  "heavy", "hedged", "hedging", "height", "held", "helmet", "help", "helper", "helpers",
  "helping", "helps", "hence", "her", "here", "heredoc", "hero", "heuristic", "heuristics",
  "hex", "hid", "hidden", "hide", "hides", "hiding", "hierarchy", "high", "higher", "highest",
  "highlight", "highlighted", "highlighting", "highlights", "highly", "him", "hinges", "hint",
  "hints", "hire", "his", "historical", "historically", "history", "hit", "hits", "hitting",
  "hoc", "hog", "hoist", "hoisted", "hold", "holder", "holding", "holdings", "holds", "hole",
  "holes", "holidays", "home", "honest", "honestly", "honesty", "honour", "honoured",
  "honouring", "honours", "hook", "hooks", "hoop", "hop", "hope", "hoped", "hops", "horizon",
  "horizontal", "host", "hosted", "hostile", "hosting", "hosts", "hot", "hotfix", "hotspot",
  "hotspots", "hour", "hourly", "hours", "house", "housekeeping", "housing", "hover", "how",
  "however", "href", "htmls", "hue", "huge", "hugh", "human", "hundred", "hundreds", "hung",
  "hunk", "hunks", "hunt", "hunting", "hunts", "hurts", "husks", "hybrid", "hydrated",
  "hydrating", "hydration", "hygiene", "hyphen", "hyphenated", "hypothesis", "hypothetical",
  "ic", "ication", "icon", "icons", "idea", "ideal", "ideally", "ideas", "idempotency",
  "idempotent", "identical", "identically", "identifiable", "identified", "identifier",
  "identifiers", "identifies", "identify", "identifying", "identity", "idiom", "idioms",
  "idle", "ids", "idx", "iew", "if", "iff", "ignore", "ignored", "ignores", "ignoring", "iii",
  "illustration", "ils", "image", "immediate", "immediately", "immune", "immunity",
  "immutable", "impact", "impeccable", "impl", "implement", "implementation",
  "implementations", "implemented", "implementer", "implementers", "implementing",
  "implements", "implication", "implicit", "implicitly", "implied", "implies", "impls",
  "imply", "implying", "import", "important", "importantly", "imported", "importing",
  "imports", "impossible", "imprecise", "impression", "improve", "improved", "improvement",
  "improvements", "in", "inaccuracies", "inactive", "inbound", "inbox", "inc", "inception",
  "incident", "incidental", "incidentally", "incidents", "incl", "include", "included",
  "includes", "including", "inclusion", "inclusive", "incoherent", "income", "incoming",
  "incomplete", "inconsistency", "inconsistent", "inconsistently", "increment", "incremental",
  "incrementally", "incremented", "increments", "incumbent", "indeed", "indefinitely",
  "indentation", "indented", "independence", "independent", "independently", "index",
  "indexed", "indexeddb", "indexes", "indexing", "indicator", "indices", "indirect",
  "indirectly", "indistinguishab", "individual", "individually", "inert", "inertness", "infer",
  "inference", "inferring", "infinite", "inflate", "inflated", "inflates", "inflating",
  "inflation", "info", "information", "informational", "informative", "infra",
  "infrastructure", "ing", "ingest", "ingested", "ingestion", "ingests", "inherent",
  "inherently", "inherit", "inherited", "inherits", "init", "initial", "initialized",
  "initially", "initials", "inject", "injectable", "injected", "injecting", "injection",
  "injects", "injuries", "injury", "ink", "inline", "inlined", "inner", "innerhtml",
  "innocent", "input", "inputs", "insert", "inserted", "inserting", "insertion", "insertions",
  "inserts", "inside", "insight", "insolvency", "insolvent", "inspect", "inspected",
  "inspecting", "inspection", "inspector", "inspects", "install", "installation", "installed",
  "installer", "installers", "installing", "installs", "instance", "instances", "instant",
  "instantly", "instead", "instinct", "instructed", "instruction", "instructions",
  "instructive", "instrument", "instrumentation", "instrumented", "insufficient", "int",
  "intact", "intake", "integer", "integers", "integrate", "integrated", "integration",
  "integrity", "intended", "intent", "intentionally", "interact", "interaction", "interactive",
  "interactively", "interacts", "interceptions", "interesting", "interface", "interfaces",
  "interim", "interleave", "interleaved", "intermediate", "intermediates", "internal",
  "internally", "internals", "international", "internationals", "internet", "interpolated",
  "interpolation", "interpretation", "interpreted", "interpreter", "interpreters", "interrupt",
  "interrupted", "interval", "intervals", "intervening", "interview", "into", "intro",
  "introduce", "introduced", "introduces", "intros", "invalid", "invalidate", "invalidated",
  "invalidates", "invalidating", "invalidation", "invariance", "invariant", "invariants",
  "invdate", "invent", "invented", "inventing", "invention", "inventory", "invents", "inverse",
  "inversion", "inversions", "invert", "inverted", "inverts", "investigate", "investigated",
  "investigating", "investigation", "investigations", "invisible", "invitational", "invites",
  "invocation", "invoice", "invoiced", "invoices", "invoicing", "invoke", "invoked", "invokes",
  "invoking", "involved", "involvement", "ion", "iplfederation", "irrelevant", "ish",
  "isolate", "isolated", "isolates", "isolating", "isolation", "ispc", "issb", "issue",
  "issued", "issues", "italic", "item", "itemised", "items", "iterate", "iterated", "iterates",
  "iterating", "iteration", "iterations", "its", "itself", "ity", "iv", "ive", "ivity",
  "james", "jan", "jarring", "javascript", "jitter", "job", "jobs", "join", "joined",
  "joining", "joins", "joke", "journal", "journalist", "journals", "journey", "jsdoc", "jsdom",
  "jsons", "judge", "judged", "judgement", "judges", "judging", "judgment", "jul", "july",
  "jump", "jumps", "jun", "junction", "june", "junk", "just", "justification", "justified",
  "justifies", "justify", "kacc", "keep", "keeper", "keeping", "keeps", "kept", "kernel",
  "key", "keyboard", "keyed", "keying", "keyless", "keyline", "keys", "keystroke", "keyword",
  "kib", "kick", "kicked", "kicking", "kickoff", "kicks", "kid", "kill", "killed", "killer",
  "killing", "kills", "kind", "kinds", "kit", "kits", "knew", "knob", "knobs", "knockout",
  "knockouts", "know", "knowing", "knowledge", "known", "knows", "kov", "kpis", "ktot", "lab",
  "label", "labeled", "labelled", "labelling", "labels", "lack", "lacked", "lacking", "lacks",
  "ladder", "lag", "lags", "laid", "land", "landed", "landing", "lands", "lane", "lanes",
  "language", "languages", "lapsed", "laptop", "large", "largely", "larger", "largest", "last",
  "latch", "late", "latency", "latent", "later", "latest", "latter", "launch", "launched",
  "launcher", "launches", "launching", "lay", "layer", "layered", "layering", "layers",
  "layout", "layouts", "lazily", "lazy", "lb", "lc", "lcov", "ld", "le", "lead", "leading",
  "leads", "leaf", "league", "leagues", "leak", "leakage", "leaked", "leaking", "leaks",
  "lean", "leans", "leapfrog", "leapfrogged", "learn", "learned", "learning", "lease", "leash",
  "least", "leave", "leaves", "leaving", "ledger", "ledgers", "left", "leftover", "leftovers",
  "leg", "legacy", "legal", "legalese", "legend", "legibility", "legible", "legitimate",
  "legitimately", "legs", "length", "lengthens", "lengths", "lens", "lenses", "less", "lesson",
  "lessons", "let", "lets", "letters", "letting", "level", "levels", "lever", "levers",
  "lexicon", "liability", "lib", "library", "libs", "licence", "licensed", "licenses",
  "licensing", "lie", "lies", "life", "lifecycle", "lifetime", "lift", "lifted", "light",
  "lighter", "lightness", "lights", "lightweight", "like", "likeliest", "likely", "likewise",
  "limit", "limitation", "limitations", "limited", "limits", "line", "lineage", "linear",
  "lineless", "lines", "lineup", "lineups", "link", "linkage", "linked", "linker", "linking",
  "links", "lint", "linter", "linting", "lintlab", "lints", "linux", "list", "listed",
  "listener", "listeners", "listing", "lists", "literal", "literally", "literals", "little",
  "live", "livebox", "lived", "livelock", "livematch", "liveness", "lives", "livetable",
  "livetick", "living", "lloyds", "lm", "load", "loaded", "loader", "loading", "loads",
  "local", "locale", "localhost", "localisation", "localization", "localized", "locally",
  "locals", "localstorage", "locate", "located", "locates", "locating", "location",
  "locations", "lock", "locked", "lockfile", "locking", "locks", "lockstep", "log", "logged",
  "logging", "logic", "logical", "login", "logon", "logout", "logs", "london", "lone", "long",
  "longer", "longest", "look", "lookahead", "looked", "looking", "looks", "lookup", "lookups",
  "loop", "loopback", "loops", "loose", "loosely", "loosened", "loosening", "looser", "lose",
  "loses", "losing", "loss", "lost", "lot", "loud", "loudly", "low", "lower", "lowercase",
  "lowercased", "lowest", "loyalty", "lt", "lucid", "luck", "luma", "luminance", "ly", "lying",
  "lysis", "machine", "machinery", "machines", "macros", "made", "magnitude", "magnitudes",
  "mail", "mailbox", "mailmerge", "main", "maintain", "maintainability", "maintainer", "major",
  "majority", "make", "makes", "making", "malformed", "malicious", "man", "manage", "managed",
  "management", "manager", "managers", "manages", "mandate", "mandated", "mandates",
  "mandatory", "mangled", "mangling", "manifest", "manifests", "manref", "manual", "manually",
  "many", "map", "mapped", "mapping", "maps", "march", "margin", "marginal", "marginally",
  "maria", "mark", "markdown", "marked", "marker", "markers", "market", "marketplace",
  "marking", "marks", "markup", "marquee", "mask", "masked", "masking", "masks", "master",
  "masthead", "match", "matchday", "matchdossier", "matched", "matcher", "matches",
  "matchfeed", "matching", "matchinput", "material", "materiality", "materially", "materials",
  "math", "maths", "matrix", "matter", "mattered", "matters", "mature", "maturity", "max",
  "maxes", "maximum", "may", "maybe", "me", "mean", "meaning", "meaningful", "meaningfully",
  "meaningless", "meanings", "means", "meant", "meantime", "meanwhile", "measurable",
  "measurably", "measure", "measured", "measurement", "measurements", "measures", "measuring",
  "mechanic", "mechanical", "mechanically", "mechanics", "mechanism", "mechanisms", "media",
  "median", "medians", "mediapipe", "medical", "medium", "meet", "meeting", "membership",
  "memberships", "memo", "memoised", "memoize", "memoized", "memories", "memory", "mental",
  "mentality", "mention", "mentioned", "mentioning", "mentions", "menu", "merely", "merge",
  "mergeability", "merged", "mergekey", "mergekeys", "merges", "merging", "merits", "mermaid",
  "meshnet", "message", "messagedisplay", "messages", "messy", "met", "meta", "metadata",
  "meter", "meters", "method", "methodically", "methods", "metric", "metrics", "mib",
  "microcopy", "mid", "middle", "midnight", "midweek", "might", "migrate", "migrated",
  "migrates", "migrating", "migration", "mileage", "milestone", "mill", "milli", "millisecond",
  "min", "mind", "mine", "miniature", "minified", "minimal", "minimise", "minimum", "minor",
  "minority", "mint", "minted", "minter", "minting", "mints", "minus", "minute", "minutes",
  "mirror", "mirrored", "mirroring", "mirrors", "misattribution", "misdiagnosed", "misfiled",
  "mislabelled", "mislead", "misleading", "misleads", "mismatched", "mismatches", "misnamed",
  "misplaced", "misread", "miss", "missed", "misses", "missing", "mistake", "mistaken",
  "mistakes", "mitigated", "mitigation", "mitigations", "mixed", "mixes", "mixing", "mme",
  "mobile", "mobility", "mock", "mockup", "mod", "modal", "moddable", "modding", "mode",
  "model", "modelled", "modelling", "models", "moderate", "modern", "modes", "modest",
  "modification", "modifications", "modified", "modify", "modifying", "modpack", "modular",
  "modularisation", "modulation", "module", "modules", "modulo", "modulus", "moment",
  "momentof", "moments", "mon", "monday", "money", "monitor", "monitored", "monitors",
  "monmouthshire", "mono", "monolith", "monolithic", "monotone", "monotonic", "monotonically",
  "month", "monthly", "months", "mood", "moot", "more", "morning", "most", "mostly", "motif",
  "motion", "mount", "mounted", "mounting", "mounts", "movable", "move", "moved", "movement",
  "movements", "moves", "moving", "ms", "msg", "mtime", "mtimes", "much", "multiple",
  "multiplier", "multiplies", "multiply", "multiset", "muse", "must", "mutable", "mutant",
  "mutants", "mutate", "mutated", "mutates", "mutating", "mutation", "mutations", "muted",
  "mutual", "mutually", "my", "myself", "mystery", "na", "nag", "nail", "naive", "name",
  "named", "names", "namespace", "namespaced", "namespaces", "naming", "nan", "narrate",
  "narrated", "narrates", "narration", "narrative", "narrow", "narrowed", "narrower",
  "narrowing", "narrowly", "narrows", "nation", "national", "nations", "native", "natively",
  "natural", "naturally", "nature", "nav", "navigate", "navigated", "navigates", "navigation",
  "nce", "nch", "ndent", "near", "nearby", "nearest", "nearly", "neat", "necessarily",
  "necessary", "ned", "need", "needed", "needing", "needle", "needs", "neg", "negative",
  "negatives", "negligible", "negnote", "negotiation", "negotiations", "neighbouring",
  "neither", "nested", "nesting", "net", "nets", "nett", "netted", "netting", "network",
  "neutral", "neutrals", "never", "new", "newer", "newest", "newgen", "newgens", "newline",
  "newlines", "newly", "newport", "news", "newspaper", "next", "ng", "nice", "nicety", "night",
  "nightly", "nil", "nine", "ninety", "nlpanel", "nly", "no", "nobody", "nod", "node", "nodes",
  "noise", "noisy", "nominal", "nominalisations", "non", "nondeterminism", "none", "nonsense",
  "nonzero", "nor", "nordvpn", "norm", "normal", "normalisation", "normalise", "normalised",
  "normalises", "normalising", "normalization", "normalized", "normalizing", "normally",
  "north", "not", "notable", "notably", "note", "noted", "notes", "nothing", "notice",
  "noticed", "notices", "notification", "notifications", "notified", "notify", "noting",
  "notion", "noun", "nouns", "nov", "now", "nowhere", "npm", "ns", "nt", "nth", "nts",
  "nuance", "nudge", "nuisance", "null", "nulls", "num", "number", "numbered", "numbering",
  "numbers", "numeral", "numerals", "numeric", "numerically", "numerous", "object",
  "objection", "objective", "objectives", "objects", "obligation", "observable", "observation",
  "observations", "observe", "observed", "observer", "observes", "obsolete", "obtained",
  "obvious", "occasional", "occasionally", "occupied", "occupies", "occur", "occurred",
  "occurrence", "occurrences", "occurs", "odd", "oddity", "of", "off", "offender", "offenders",
  "offending", "offer", "offered", "offering", "offers", "office", "official", "officials",
  "offline", "offset", "offsets", "offsetting", "often", "oice", "oicing", "old", "older",
  "ollama", "omission", "omit", "omits", "omitted", "omitting", "on", "once", "one",
  "onedrive", "ones", "ongoing", "online", "only", "onprogress", "ons", "onstop", "onto",
  "onward", "ooms", "op", "opaque", "opcode", "opcodes", "open", "opened", "opener",
  "openfile", "opening", "openings", "openly", "openpyxl", "opens", "operate", "operation",
  "operational", "operations", "opinion", "opponent", "opponents", "opposing", "opposite",
  "ops", "option", "optional", "optionally", "options", "opts", "opus", "or", "oracle",
  "orange", "orchestration", "orchestrator", "ordbuckets", "order", "orderdate", "ordered",
  "ordering", "ordernumber", "orders", "ordinal", "ordinals", "ordinary", "org",
  "organisation", "organisational", "organised", "orientation", "oriented", "orienting",
  "origin", "original", "originally", "originals", "originates", "origins", "orphan",
  "orphaned", "orphans", "orthogonal", "ory", "other", "others", "otherwise", "ount", "our",
  "ours", "out", "outage", "outcome", "outcomes", "outer", "outfield", "outline", "outlive",
  "outlived", "outlook", "output", "outputs", "outputting", "outrank", "outranks", "outright",
  "outside", "outstanding", "ovacc", "ovd", "over", "overall", "overdraw", "overdue",
  "overdueamt", "overflow", "overflows", "overhead", "overlaid", "overlap", "overlapping",
  "overlaps", "overlay", "overlays", "overloaded", "overnight", "overpay", "overridable",
  "overridden", "override", "overrides", "overriding", "overshoot", "overshoots", "oversight",
  "oversized", "overstated", "overstates", "overtaken", "overview", "overwrite", "overwrites",
  "overwriting", "overwritten", "overwrote", "ow", "owe", "owed", "owes", "own", "owned",
  "owner", "ownership", "owning", "owns", "paced", "paces", "pacing", "pack", "package",
  "packages", "packaging", "packs", "padding", "page", "pages", "paid", "paidup", "pain",
  "paint", "painted", "paints", "pair", "paired", "pairing", "pairings", "pairs", "palette",
  "palettes", "pane", "panel", "panels", "panes", "panic", "panics", "paper", "papered",
  "papers", "paragraph", "paragraphs", "parallel", "parallelise", "parallelism", "param",
  "parameter", "parameterised", "parameters", "params", "parent", "parentheses",
  "parenthetical", "parked", "parking", "parks", "parody", "parse", "parseable", "parsed",
  "parser", "parsererror", "parsers", "parses", "parsing", "part", "partial", "participation",
  "particular", "particularly", "partition", "partitioning", "parts", "pass", "passage",
  "passed", "passes", "passing", "passive", "passthrough", "password", "past", "paste",
  "pasted", "pasting", "patch", "patched", "patches", "patching", "path", "paths", "pathspec",
  "patience", "patient", "pattern", "patterns", "paul", "pause", "paused", "pauses", "pay",
  "payable", "payer", "payers", "paying", "payload", "payloads", "payment", "payments",
  "payoff", "payroll", "pays", "pcnotice", "pdfs", "peak", "peaks", "peek", "peer", "peers",
  "pembrigg", "penalties", "penalty", "pence", "pending", "penny", "pens", "people", "per",
  "perceived", "percentage", "perception", "perf", "perfect", "perfectly", "performance",
  "performed", "performs", "perhaps", "period", "periodic", "periods", "permanent",
  "permanently", "permission", "permissions", "permits", "permitted", "persist", "persisted",
  "persistence", "persistent", "persisting", "persists", "person", "persona", "personal",
  "personality", "personalkey", "personalkeys", "personas", "personnel", "persons", "persuade",
  "perturb", "perturbs", "pet", "phantom", "phase", "phases", "phenomenon", "philosophy",
  "phone", "phones", "phrase", "phrases", "phrasing", "physical", "physically", "physio",
  "pick", "picked", "picker", "picking", "picks", "pickup", "picture", "piece", "pieces",
  "piggyback", "pile", "pill", "pillar", "pills", "ping", "pinned", "pinning", "pins", "pip",
  "pipe", "piped", "pipeline", "pipes", "pitch", "pitchsvg", "pivot", "place", "placed",
  "placeholder", "placeholders", "placement", "placementid", "placements", "places", "plain",
  "plainly", "plainness", "plan", "planned", "planning", "plans", "planted", "plasma",
  "platform", "platforms", "plausibility", "plausible", "plausibleline", "plausibly", "play",
  "playable", "playbook", "played", "player", "playerline", "players", "playing", "playoff",
  "playoffs", "plays", "playtest", "playtesting", "playwright", "pleasantries", "please",
  "plug", "plugin", "plugins", "plumbing", "plural", "plus", "point", "pointed", "pointer",
  "pointers", "pointing", "points", "poison", "poisoned", "polarity", "pole", "policies",
  "policy", "polish", "politely", "poll", "poller", "polling", "polls", "pool", "pools",
  "poor", "popover", "populate", "populated", "populates", "population", "populations",
  "popup", "port", "portable", "portal", "ported", "portion", "ports", "position",
  "positional", "positionally", "positioned", "positions", "positive", "positively",
  "positives", "possession", "possessions", "possible", "possibly", "post", "posted",
  "posting", "postings", "posts", "posttooluse", "posture", "potentially", "pound", "pounds",
  "power", "powershell", "powys", "practical", "practice", "pragmatic", "pre", "preamble",
  "precede", "preceded", "precedence", "precedent", "precedes", "precise", "precisely",
  "precision", "precondition", "predate", "predated", "predates", "predating", "predicate",
  "predicates", "predicted", "prediction", "predictions", "prefer", "preference",
  "preferences", "preferred", "prefers", "prefix", "prefixed", "prefixes", "preflight",
  "pregame", "premature", "premier", "premise", "premises", "prep", "prepaid", "prepare",
  "prepared", "preparing", "prepayment", "prepayments", "prepended", "prepends",
  "prerequisite", "prerequisites", "prescribes", "presence", "present", "presentation",
  "presentational", "presented", "presenting", "presents", "preservation", "preserve",
  "preserved", "preserves", "preserving", "presim", "press", "pressbox", "pressed", "pressing",
  "pressure", "presumably", "pretend", "pretending", "pretooluse", "prev", "prevent",
  "prevented", "prevents", "previewed", "previews", "previous", "previousband", "previously",
  "price", "priced", "prices", "pricing", "primaries", "primary", "prime", "priming",
  "primitive", "primitives", "principle", "principled", "principles", "print", "printed",
  "printer", "printing", "prints", "prior", "priorities", "priority", "pristine", "privacy",
  "privates", "prize", "pro", "probability", "probably", "probe", "probed", "probes",
  "probing", "problem", "problems", "procedural", "procedure", "procedures", "proceed",
  "proceeding", "proceeds", "process", "processed", "processes", "processing", "produce",
  "produced", "producer", "producers", "produces", "producing", "product", "production",
  "profile", "profiler", "profiles", "profiling", "programmaticall", "programme", "progress",
  "progressing", "progressive", "project", "projection", "projections", "projects", "promise",
  "promised", "promises", "promising", "promote", "promoted", "promotes", "promotion",
  "prompt", "prompted", "prompting", "prompts", "pronoun", "proof", "proofs", "prop",
  "propagate", "propagated", "propagates", "propagation", "proper", "properly", "properties",
  "property", "proposal", "proposals", "propose", "proposed", "proposes", "proposing", "props",
  "prose", "prospect", "prospects", "protect", "protected", "protecting", "protection",
  "protects", "protocol", "prototype", "provable", "provably", "prove", "proved", "proven",
  "provenance", "proves", "provide", "provided", "provider", "provides", "proving",
  "provisional", "provisioned", "proxies", "proximity", "proxy", "prs", "prune", "pruned",
  "pruning", "psmux", "pts", "pub", "pubkey", "public", "publication", "publicly", "publish",
  "publishable", "published", "publishes", "publishing", "pull", "pulled", "pulling", "pulls",
  "pulse", "punch", "punctuation", "pundit", "pundits", "purchase", "pure", "purely", "purity",
  "purple", "purpose", "purposes", "push", "pushed", "pushes", "pushing", "put", "puts",
  "putting", "px", "py", "pypdf", "pyramid", "pyramids", "python", "pythons", "qty", "quaffle",
  "qualification", "qualifies", "qualifying", "quality", "quantified", "quantify",
  "quantifying", "quantitative", "quantities", "quantity", "quarantined", "quarter", "queried",
  "queries", "query", "queryable", "querying", "question", "questions", "queue", "queued",
  "queues", "queuing", "quick", "quickly", "quidditch", "quiet", "quieter", "quietly", "quirk",
  "quit", "quite", "quota", "quotation", "quote", "quoted", "quotes", "quoting", "race",
  "races", "racing", "radio", "radius", "rail", "raise", "raised", "raises", "raising", "ran",
  "random", "randomness", "range", "ranges", "rank", "ranked", "ranking", "ranks", "rare",
  "rarely", "ratchet", "ratchets", "rate", "rates", "rather", "ratification", "ratifications",
  "ratified", "ratify", "ratifying", "ratings", "ratio", "ration", "rationale", "ratios",
  "raw", "rc", "rd", "re", "reach", "reachability", "reachable", "reached", "reaches",
  "reaching", "reaction", "reactive", "read", "readability", "readable", "readback", "reader",
  "readers", "readiness", "reading", "readmes", "readout", "reads", "readsharedbands", "ready",
  "real", "realistic", "realistically", "really", "ream", "reaped", "reappear", "reason",
  "reasonable", "reasonably", "reasoned", "reasoning", "reasons", "reassigned", "reassuring",
  "rebase", "rebased", "rebasing", "reboot", "rebuild", "rebuildable", "rebuilding",
  "rebuilds", "rebuilt", "recalculates", "recalibrated", "recalibration", "recall", "recalled",
  "recalling", "recap", "receipt", "receipts", "receive", "received", "receives", "recency",
  "recent", "recently", "recheck", "recipe", "recipient", "reclaim", "reclaimed", "reclass",
  "recognise", "recognised", "recognized", "recollection", "recommend", "recommendations",
  "recommended", "recommending", "recommends", "recompute", "recomputed", "recomputes",
  "recomputing", "reconcile", "reconciled", "reconciler", "reconciles", "reconciliation",
  "reconciliations", "reconciling", "reconnect", "reconsider", "reconstruct", "reconstructed",
  "reconstructing", "reconstruction", "record", "recorded", "recording", "records", "recount",
  "recoupling", "recover", "recoverable", "recovered", "recovering", "recovers", "recovery",
  "recstate", "rect", "recur", "recurred", "recurring", "recurs", "recurses", "recursive",
  "redacted", "reddit", "redesign", "redirect", "redirected", "redirects", "rediscover",
  "redo", "redoing", "redrawn", "reds", "reduce", "reduced", "reduces", "reduction",
  "redundant", "ref", "refactor", "refactored", "refactors", "referee", "reference",
  "referenced", "referenceerror", "references", "referencing", "refers", "refill", "refills",
  "refine", "refinement", "refinements", "reflect", "reflectcuts", "reflected", "reflects",
  "refocus", "reframed", "reframes", "reframing", "refresh", "refreshed", "refreshes",
  "refreshing", "refs", "refunded", "refunds", "refusal", "refusals", "refuse", "refused",
  "refuses", "refusing", "refutation", "refutations", "refute", "refutes", "regardless",
  "regen", "regenerable", "regenerate", "regenerated", "regenerates", "regenerating",
  "regeneration", "regex", "regexes", "region", "regions", "register", "registered",
  "registering", "registers", "registration", "registrations", "registries", "registry",
  "regress", "regressed", "regresses", "regression", "regressions", "regular", "regulation",
  "reinforces", "reintroduce", "reintroduced", "reintroducing", "reject", "rejected",
  "rejecting", "rejection", "rejections", "rejects", "relabel", "relabelling", "relate",
  "related", "relationship", "relative", "relaunch", "relaunched", "relaunching", "relax",
  "relay", "relaying", "release", "released", "releases", "relegation", "relevance",
  "relevant", "reliability", "reliable", "reliably", "relies", "reload", "reloaded", "reloads",
  "relocated", "relocation", "rely", "relying", "remain", "remainder", "remaining", "remains",
  "remedy", "remember", "remembered", "remembering", "remembers", "reminder", "remit",
  "remits", "remittance", "remittances", "remitted", "remote", "remotely", "removal",
  "removals", "remove", "removed", "removeitem", "removes", "removing", "rename", "renamed",
  "renames", "renaming", "render", "rendered", "renderer", "renderers", "rendering",
  "renderrows", "renders", "rendezvous", "renew", "renewal", "renumber", "renumbered",
  "renumbering", "reopen", "reopened", "reopening", "reorder", "reordered", "reordering",
  "reorders", "repaint", "repaintall", "repaints", "repair", "repaired", "repairing",
  "repairs", "repeat", "repeated", "repeatedly", "repeating", "repeats", "repetition",
  "replace", "replaced", "replacement", "replacements", "replaces", "replacing", "replay",
  "replayability", "replayable", "replayed", "replays", "replicate", "replicating", "replies",
  "reply", "replying", "repo", "repoint", "repointed", "repointing", "report", "reported",
  "reporting", "reports", "repos", "repository", "represent", "representable",
  "representative", "represents", "repro", "reproduce", "reproduced", "reproduces",
  "reproducibility", "reproducible", "reproducing", "reproduction", "republish", "republished",
  "republishing", "reputation", "reputations", "request", "requested", "requests", "require",
  "required", "requirement", "requirements", "requires", "requiring", "reroll", "rerun",
  "rerunning", "reruns", "reschedule", "rescoped", "rescue", "rescues", "research",
  "reselecting", "reserve", "reserved", "reserves", "reset", "resets", "reshape", "reshapes",
  "residency", "resident", "residual", "residuals", "residue", "resize", "resolution",
  "resolvable", "resolve", "resolved", "resolver", "resolves", "resolving", "resource",
  "respect", "respected", "respectively", "respects", "respond", "response", "responses",
  "restart", "restarted", "restarting", "restarts", "restate", "restated", "restating",
  "restore", "restored", "restores", "restoring", "restricted", "restriction", "restructure",
  "restructured", "restructuring", "rests", "restyling", "resubmit", "result", "resulting",
  "results", "resum", "resumable", "resume", "resumed", "resumes", "resuming", "resurrect",
  "resurrects", "retain", "retained", "retaining", "retains", "retake", "retarget",
  "retargeted", "retention", "retire", "retired", "retires", "retiring", "retract",
  "retraction", "retried", "retries", "retrieval", "retroactively", "retry", "retrying",
  "retune", "return", "returned", "returning", "returns", "retyped", "reusable", "reuse",
  "reused", "reuses", "reusing", "reveal", "revealed", "revealing", "reveals", "revenue",
  "reverb", "reverse", "reversed", "reverses", "reversible", "reversing", "revert", "reverted",
  "revertible", "reverting", "reverts", "review", "reviewable", "reviewed", "reviewer",
  "reviewers", "reviewing", "reviews", "revise", "revised", "revising", "revision", "revisit",
  "rewind", "rewinding", "reword", "reworded", "rework", "reworked", "reworking", "rewrite",
  "rewrites", "rewriting", "rewritten", "rewrote", "rgb", "rhythm", "rich", "richdb", "richer",
  "ride", "rides", "riding", "rig", "right", "rights", "rigorous", "rigorously", "ring",
  "ripple", "rise", "rises", "risk", "riskiest", "risks", "risky", "rival", "rivalries",
  "rivals", "roadmap", "roar", "robust", "robustly", "robustness", "rode", "role", "roles",
  "roll", "rollback", "rolled", "rolling", "rollout", "rollover", "rolls", "rollup", "rollups",
  "room", "root", "roots", "rose", "roster", "rosters", "rot", "rotate", "rotated", "rotates",
  "rotation", "rotting", "rough", "roughly", "round", "rounded", "rounding", "rounds", "route",
  "routed", "router", "routes", "routine", "routinely", "routing", "row", "rows", "rs",
  "rugby", "rule", "rulebook", "ruled", "rules", "ruleset", "rulesets", "ruling", "rulings",
  "run", "runbook", "runes", "rung", "runnable", "runner", "runners", "running", "runofplay",
  "runs", "runtime", "rush", "rushed", "rust", "rustc", "rustfmt", "rustup", "rving", "ry",
  "sabotage", "sacked", "sacking", "safari", "safe", "safely", "safer", "safest",
  "safetensors", "safety", "sage", "said", "sales", "salesforce", "salt", "salvage",
  "salvageable", "salvaged", "salvation", "same", "sample", "sampled", "samples", "sampling",
  "sanctioned", "sandbox", "sane", "sanitisation", "sanitize", "sanity", "sans", "sas", "sat",
  "satisfied", "satisfies", "satisfy", "satisfying", "saturated", "saturating", "saturday",
  "saturdays", "save", "saved", "savedat", "saves", "saving", "saw", "say", "saying", "says",
  "sbm", "sbmatch", "scaffold", "scaffolded", "scaffolder", "scaffolding", "scaffolds",
  "scalar", "scalars", "scale", "scaled", "scales", "scaling", "scan", "scannability",
  "scanned", "scanner", "scanning", "scans", "scarce", "scattered", "scenario", "scenarios",
  "scene", "sch", "schedule", "scheduled", "scheduler", "schedules", "scheduling", "schema",
  "schemas", "scheme", "school", "science", "scientific", "scope", "scoped", "scopes",
  "scoping", "score", "scorebug", "scored", "scoreline", "scorelines", "scorer", "scorers",
  "scores", "scoring", "scout", "scouted", "scouting", "scouts", "scratch", "scratchpad",
  "screen", "screens", "screenshot", "screenshots", "script", "scripted", "scripts", "scroll",
  "scrollable", "scrollback", "scrollbar", "scrolled", "scroller", "scrolling", "scrolls",
  "scrollwidth", "seal", "sealed", "sealing", "seam", "seams", "search", "searchable",
  "searched", "searches", "searching", "season", "seasons", "seat", "second", "secondary",
  "seconds", "secret", "section", "sections", "secure", "security", "sed", "see", "seed",
  "seeded", "seeding", "seeds", "seeing", "seeker", "seems", "seen", "sees", "seg", "segment",
  "segmented", "segments", "select", "selectable", "selected", "selecting", "selection",
  "selections", "selector", "selectors", "selects", "semantic", "semantically", "semantics",
  "semver", "send", "sender", "sending", "sends", "senior", "sense", "sensible", "sensitive",
  "sensitivity", "sensor", "sent", "sentence", "sentences", "sentinel", "sentinels", "sep",
  "separable", "separate", "separated", "separately", "separates", "separating", "separator",
  "sequence", "sequenced", "sequences", "sequencing", "sequential", "sequentially", "serde",
  "serial", "serialisation", "serialise", "serialised", "serialises", "serialization",
  "serialize", "serialized", "serializer", "serializes", "serially", "series", "serious",
  "serve", "served", "server", "servers", "serves", "service", "services", "serving",
  "session", "sessions", "setitem", "sets", "setting", "settings", "settingsmodal", "settle",
  "settled", "settlement", "settlements", "settles", "settling", "setup", "seven", "several",
  "severe", "sh", "shadow", "shadowing", "shadows", "shall", "shallow", "shape", "shaped",
  "shapes", "share", "shareable", "shared", "sharepoint", "shares", "sharing", "sharp",
  "sharpen", "sharpened", "sharpening", "sharpens", "sharper", "sharpest", "sharply", "shas",
  "she", "sheet", "sheets", "shell", "shells", "shield", "shields", "shift", "shifted",
  "shifting", "shifts", "shim", "shims", "ship", "shippable", "shipped", "shipping", "ships",
  "shock", "shooter", "shootout", "short", "shortcut", "shorten", "shortened", "shortening",
  "shorter", "shortest", "shortfall", "shorthand", "shortlist", "shortly", "shot", "shots",
  "should", "shout", "show", "showcase", "showed", "showing", "shown", "shows", "shrank",
  "shrink", "shrinking", "shrinks", "shuffles", "shut", "sibling", "siblings", "side",
  "sidebar", "sidecar", "sidecars", "sides", "sidesteps", "sight", "sign", "signal", "signals",
  "signature", "signatures", "signed", "signer", "significant", "signing", "signings", "signs",
  "silence", "silenced", "silencing", "silent", "silently", "sim", "similar", "similarity",
  "similarly", "simple", "simpler", "simplest", "simplification", "simplified", "simplifies",
  "simplify", "simply", "simulate", "simulated", "simulates", "simulating", "simulation",
  "simultaneous", "simultaneously", "since", "single", "singleton", "singular", "sink",
  "siren", "sit", "site", "sites", "sitive", "sits", "sitting", "situation", "six", "sixteen",
  "sixth", "size", "sized", "sizes", "sizing", "skeleton", "sketch", "skew", "skill", "skills",
  "skim", "skin", "skins", "skip", "skipped", "skipping", "skips", "slack", "slashes", "slate",
  "slice", "sliced", "slices", "sliders", "slight", "slightly", "slim", "slip", "slipped",
  "slips", "slot", "slots", "slow", "slower", "slowing", "slowly", "slug", "slugs", "small",
  "smaller", "smallest", "smart", "smartmerge", "smartscreen", "smell", "smells", "smoke",
  "smooth", "smuggled", "snag", "snapshot", "snapshots", "snapshotted", "snippet", "snippets",
  "snitch", "so", "social", "socket", "soft", "soften", "software", "solely", "solid", "solo",
  "solution", "solutions", "solve", "solved", "solvency", "solves", "some", "somehow",
  "someone", "something", "sometimes", "somewhere", "sonnet", "soon", "sooner", "sophie",
  "sorry", "sort", "sortable", "sorted", "sorting", "sorts", "sound", "soundness", "sounds",
  "source", "sourced", "sources", "sourcing", "space", "spaced", "spaces", "spacing", "span",
  "spanning", "spans", "spare", "spark", "sparkline", "sparse", "spatial", "spawn", "spawned",
  "spawns", "speak", "speaker", "speaking", "speaks", "spec", "specced", "special", "specific",
  "specifically", "specification", "specifications", "specificity", "specifics", "specified",
  "specifies", "specify", "specs", "speculative", "speed", "speeds", "spelled", "spelling",
  "spellings", "spells", "spend", "spending", "spends", "spent", "spfx", "spike", "spikes",
  "spill", "spin", "spine", "spinner", "spinning", "spins", "spirit", "splash", "splice",
  "spliced", "splices", "split", "splits", "splitting", "sport", "sportpacks", "sports",
  "spot", "spots", "spotted", "sprawl", "spread", "spreads", "spreadsheet", "sproc",
  "spurious", "spuriously", "sqlite", "sqlites", "squad", "squads", "square", "squarely",
  "squash", "src", "sret", "srs", "stability", "stable", "stack", "stacked", "stacking",
  "stacks", "stadium", "stadiums", "staff", "staffplan", "stage", "staged", "stages",
  "stagger", "staging", "stakes", "stale", "staleness", "stall", "stalled", "stalls", "stamp",
  "stamped", "stamping", "stamps", "stance", "stand", "standalone", "standard",
  "standardisation", "standardise", "standards", "standing", "standings", "standout", "stands",
  "start", "started", "starter", "starting", "starts", "startup", "starved", "stash", "stat",
  "state", "stated", "stateful", "stateless", "statement", "statements", "states", "static",
  "statically", "stating", "statistical", "stats", "stature", "status", "statusline",
  "statutory", "stay", "stayed", "staying", "stays", "stderr", "stdin", "stdlib", "stdout",
  "steadily", "steady", "steer", "steering", "step", "stepped", "stepper", "stepping", "steps",
  "stic", "stick", "sticks", "sticky", "still", "stmt", "stock", "stood", "stop", "stopgap",
  "stoppage", "stopped", "stopping", "stops", "storage", "store", "stored", "stores",
  "storing", "storm", "story", "straddle", "straddles", "stragglers", "straight",
  "straightforward", "strand", "stranded", "strands", "strategic", "strategy", "stratum",
  "stray", "stream", "streaming", "streams", "strength", "strengthen", "strengthened",
  "strengthening", "strengths", "stretch", "stretches", "strict", "stricter", "strictly",
  "striker", "strikers", "strikethrough", "string", "stringify", "strings", "strip", "stripe",
  "stripped", "stripping", "strips", "strong", "stronger", "strongest", "strongly", "struck",
  "struct", "structural", "structurally", "structure", "structured", "structuredoutpu",
  "structures", "stub", "stubbed", "stubs", "stuck", "studio", "study", "style", "styled",
  "styles", "stylesheet", "stylesheets", "styling", "sub", "subagent", "subagents",
  "subagentstop", "subcommand", "subcommands", "subdirectories", "subdirectory", "subfolders",
  "subhead", "subject", "subjects", "submission", "submit", "submitted", "submitting",
  "submodules", "subnav", "subprocess", "subs", "subscription", "subsequent", "subset",
  "substance", "substantial", "substantially", "substantive", "substitute", "substituted",
  "substitutes", "substitution", "substitutions", "substrate", "substring", "subtle",
  "subtler", "subtlety", "subtraction", "subtracts", "subtree", "succeeded", "succeeds",
  "success", "successful", "successfully", "successive", "successor", "such", "sufficient",
  "suffix", "suffixes", "suggest", "suggested", "suggesting", "suggestion", "suggestions",
  "suggests", "suite", "suited", "suites", "suits", "sum", "summaries", "summarised",
  "summarising", "summary", "summed", "summer", "summing", "summit", "sums", "sun", "sunday",
  "supersede", "supersedes", "superset", "supplied", "supplier", "supplies", "supply",
  "support", "supported", "supporting", "supports", "supposed", "suppress", "suppressed",
  "suppresses", "suppressing", "suppression", "sure", "surface", "surfaced", "surfaces",
  "surfacing", "surgery", "surgical", "surname", "surprise", "surprising", "surrounding",
  "survey", "surveying", "survivable", "survival", "survive", "survived", "survives",
  "surviving", "survivor", "survivors", "suspect", "suspected", "suspects", "suspense",
  "suspicion", "suspicious", "suspiciously", "svelte", "swallow", "swallowed", "swallowing",
  "swallows", "swap", "swapped", "swapping", "swaps", "sweep", "sweeper", "sweeping", "sweeps",
  "swept", "swing", "swings", "switch", "switched", "switcher", "switches", "switching",
  "symbol", "symbols", "symmetric", "symmetrical", "symmetry", "symptom", "sync", "synced",
  "synchronous", "synchronously", "syncing", "syncs", "syntactically", "syntax", "synth",
  "synthesis", "synthesise", "synthesised", "synthesises", "synthesize", "synthesized",
  "synthetic", "system", "systematic", "systematically", "systemic", "systems", "tab",
  "tabbar", "tabbed", "table", "tabled", "tables", "tabs", "tackle", "tackles", "tactic",
  "tactical", "tactics", "tag", "tagged", "tagging", "tags", "tail", "tailing", "tailnet",
  "tailscale", "take", "taken", "takeover", "taker", "takes", "taking", "talk", "talks",
  "tally", "target", "targeted", "targeting", "targets", "tary", "task", "tasks", "taste",
  "taught", "tauri", "tax", "taxonomy", "tbody", "teaches", "teaching", "team", "teams",
  "teamsync", "teamviewer", "teardown", "technical", "technically", "technique", "ted",
  "teeth", "tell", "telling", "tells", "temp", "temperament", "template", "templates", "tempo",
  "temporarily", "temporary", "ten", "tends", "tens", "tense", "tension", "tenure", "term",
  "terminal", "terminated", "terminates", "termination", "terminator", "terminology",
  "termsof", "ternary", "terra", "terrace", "territory", "terse", "test", "testable", "tested",
  "testing", "tests", "text", "textbook", "texts", "texture", "tfoot", "th", "than", "thank",
  "thanks", "that", "the", "their", "theirs", "them", "theme", "themes", "themselves", "then",
  "theoretical", "theorising", "theory", "there", "therefore", "these", "thesis", "they",
  "thin", "thing", "things", "think", "thinking", "thinks", "third", "thirteen", "this",
  "thornmere", "thorough", "thoroughly", "those", "though", "thought", "thousands", "thrash",
  "thread", "threaded", "threading", "threads", "threat", "three", "threshold", "thresholds",
  "threw", "throttle", "throttled", "throttling", "through", "throughout", "throughput",
  "throw", "throwaway", "throwing", "thrown", "throws", "thus", "tical", "tick", "ticked",
  "ticker", "ticking", "tickreport", "ticks", "tics", "tidied", "tidy", "tidying", "tie",
  "tiebreak", "tied", "tier", "tiers", "ties", "tight", "tighten", "tightened", "tightening",
  "tighter", "tile", "tiles", "time", "timed", "timeline", "timeout", "timeouts", "timer",
  "timers", "times", "timesheet", "timesheets", "timestamp", "timestamped", "timestamps",
  "timezone", "timing", "timings", "tinted", "tints", "tiny", "tion", "tip", "tips", "title",
  "titled", "titles", "tive", "tmp", "tmux", "to", "toast", "today", "together", "toggle",
  "toggled", "toggles", "toggling", "token", "tokeniser", "tokens", "told", "tolerance",
  "tolerances", "tolerant", "tolerate", "tolerated", "tolerates", "tombstone", "tombstones",
  "tombstoning", "toml", "tomorrow", "tone", "tonight", "too", "took", "tool", "toolbar",
  "toolchain", "tooling", "tools", "tooltip", "tooltips", "top", "topbar", "topbarh", "topic",
  "topics", "topology", "tops", "torfaen", "torn", "tot", "total", "totality", "totalling",
  "totals", "touch", "touched", "touches", "touching", "touchline", "tour", "toward",
  "towards", "tower", "toxic", "trace", "traced", "traces", "tracing", "track", "tracked",
  "tracker", "tracking", "tracks", "tractable", "trade", "trades", "trading", "traffic",
  "trail", "trailing", "train", "training", "trains", "trait", "trajectory", "tral", "tranche",
  "tranches", "transaction", "transactions", "transcript", "transcription", "transcripts",
  "transfer", "transfers", "transform", "transient", "transit", "transition", "transitions",
  "translation", "transparent", "transport", "trantype", "trap", "trapped", "traps", "travel",
  "travels", "treat", "treated", "treating", "treatment", "treats", "tree", "trees", "trend",
  "trial", "trick", "tried", "tries", "trigger", "triggerable", "triggered", "triggering",
  "triggers", "trim", "trimmed", "trimming", "trims", "trip", "triple", "tripped", "tripping",
  "trips", "tripwire", "trivial", "trivially", "trophy", "true", "truly", "truncate",
  "truncated", "truncates", "truncating", "truncation", "trunk", "trust", "trusted",
  "trusting", "trusts", "trustworthy", "truth", "truthful", "truthy", "try", "trying", "tsc",
  "tuesday", "tuition", "tuned", "tuning", "tunnel", "tuple", "ture", "turn", "turned",
  "turning", "turnover", "turnovers", "turns", "tweak", "twelve", "twenty", "twice", "twin",
  "twins", "two", "tx", "txdays", "txn", "txns", "ty", "tying", "typecheck", "typed", "types",
  "typescript", "typeset", "typical", "typically", "typing", "typo", "typographic",
  "typography", "ubuntu", "unable", "unaffected", "unaided", "unambiguous", "unasked",
  "unassigned", "unattended", "unattributed", "unavailable", "unavoidable", "unblock",
  "unblocked", "unblocking", "unblocks", "unbounded", "uncapped", "uncaught", "uncertainty",
  "unchanged", "unchecked", "unclosed", "uncomfortable", "uncommitted", "uncompressed",
  "unconditional", "unconditionally", "unconfirmed", "unconstrained", "uncontended",
  "uncovered", "undated", "undecided", "undeclared", "undefined", "under", "underlying",
  "underneath", "understand", "understanding", "understated", "understatement", "understates",
  "understood", "underway", "undisturbed", "undo", "undocumented", "undone", "unenforced",
  "unescaped", "unevenly", "unexercised", "unexpected", "unexported", "unfiled", "unfiltered",
  "unfinished", "unfixed", "ungated", "unguarded", "unhandled", "unicode", "unification",
  "unified", "uniform", "uniformity", "uniformly", "unilaterally", "unindexed", "union",
  "unioned", "unions", "unique", "uniquely", "uniqueness", "united", "units", "universal",
  "universe", "unknown", "unless", "unlike", "unlikely", "unlinked", "unlisted", "unload",
  "unloaded", "unlock", "unlocked", "unlocks", "unmapped", "unmarked", "unmatched",
  "unmeasured", "unmentioned", "unmerged", "unmodified", "unmounts", "unmoved", "unmutated",
  "unnecessary", "unnoticed", "unowned", "unparseable", "unparsed", "unpatched", "unpersisted",
  "unpinnable", "unpinned", "unplayed", "unplug", "unposted", "unprompted", "unproven",
  "unpublished", "unpushed", "unreachable", "unread", "unreadable", "unreconciled",
  "unrecorded", "unrecoverable", "unrelated", "unreleased", "unreliable", "unresolvable",
  "unresolved", "unsafe", "unsaved", "unscoped", "unset", "unshipped", "unsigned", "unspent",
  "unstarted", "unstyled", "unt", "untestable", "untested", "untick", "until", "untouched",
  "untracked", "untrusted", "unusable", "unused", "unusual", "unusually", "unverifiable",
  "unwatched", "up", "upcoming", "update", "updated", "updater", "updates", "updating",
  "upgrade", "upgraded", "upgrades", "upload", "uploads", "upon", "upper", "upstream", "ure",
  "urgent", "urls", "us", "usability", "usable", "usage", "usages", "use", "used", "useful",
  "usefully", "useless", "user", "userkeys", "userpromptsubmi", "users", "uses", "using",
  "usort", "usual", "usually", "vacancy", "vacuity", "vacuous", "vacuously", "vague", "val",
  "vale", "valid", "validate", "validated", "validates", "validating", "validation",
  "validator", "validators", "valuable", "valuation", "value", "values", "vanish", "vanished",
  "vanishes", "var", "varchar", "variable", "variables", "variance", "variances", "variant",
  "variants", "variation", "varies", "variety", "vars", "vary", "varying", "vcdlg", "ve",
  "vector", "vectors", "vendor", "vendored", "vendoring", "venue", "venues", "verb",
  "verbatim", "verbose", "verdicts", "verifiable", "verifiably", "verification",
  "verifications", "verified", "verifier", "verifiers", "verifies", "verify", "verifying",
  "version", "versioning", "versions", "versus", "vertical", "very", "veto", "via", "viable",
  "view", "viewer", "viewing", "viewport", "views", "vintage", "violate", "violates",
  "violating", "violation", "violations", "virtual", "visibility", "visible", "visibly",
  "visitor", "visual", "visually", "visuals", "vocab", "vocabulary", "voice", "voiced",
  "voices", "void", "volatile", "voltage", "volume", "volumes", "vs", "vulkan", "wages",
  "wait", "waited", "waiting", "waits", "waiver", "wake", "wales", "walk", "walked", "walker",
  "walking", "walks", "wall", "want", "wanted", "wanting", "wants", "warm", "warn", "warned",
  "warning", "warnings", "warns", "wart", "was", "wash", "wasmi", "waste", "wasted", "watch",
  "watchable", "watchdog", "watched", "watcher", "watchers", "watches", "watching", "water",
  "watermark", "wave", "waves", "way", "ways", "wbits", "we", "weak", "weaken", "weakened",
  "weakening", "weaker", "weakest", "weakness", "weaknesses", "wear", "wearing", "web",
  "webhook", "webview", "wed", "wedge", "wedged", "wednesday", "week", "weekday", "weekend",
  "weekending", "weekends", "weekly", "weeks", "weigh", "weight", "weighted", "weights",
  "welcome", "well", "welsh", "went", "were", "wet", "what", "whatever", "whatsoever", "when",
  "whenever", "where", "whereas", "wherever", "whether", "which", "whichever", "while",
  "whistle", "white", "whitelist", "whitelisted", "whitelisting", "whitelists", "whitespace",
  "who", "whoever", "whole", "wholesale", "wholly", "whom", "whose", "whosel", "why", "wide",
  "widen", "widened", "widening", "widens", "wider", "widget", "width", "widths", "wild",
  "wildly", "will", "williams", "win", "window", "windowed", "windowing", "windows", "winget",
  "winner", "winners", "winning", "wins", "winter", "wipe", "wire", "wired", "wires", "wiring",
  "wirral", "wish", "with", "withdraw", "withdrew", "withheld", "within", "without", "witness",
  "wk", "wks", "woken", "won", "word", "worded", "wording", "wordlist", "wordlists", "words",
  "work", "workable", "workaround", "workbench", "workbook", "workbooks", "worked", "worker",
  "workers", "workflow", "workflows", "working", "workingtactics", "worklist", "workload",
  "works", "workshop", "workspace", "workstream", "workstreams", "worktree", "worktrees",
  "world", "worldgen", "worlds", "worry", "worse", "worst", "worth", "worthless", "would",
  "wrap", "wrapped", "wrapper", "wrappers", "wrapping", "wraps", "wrinkle", "writable",
  "write", "writer", "writers", "writes", "writesharedband", "writing", "written", "wrong",
  "wrongly", "wrote", "wt", "wtpack", "wtsave", "www", "xg", "xis", "xlsx", "xmls", "year",
  "years", "yes", "yesterday", "yet", "yield", "yielding", "yields", "yml", "you", "your",
  "yours", "yourself", "youth", "yr", "yrs", "ysgol", "zero", "zeroed", "zeros", "zips",
  "zone", "zones", "zstd"
]);

/**
 * Words that are almost never capitalised in the middle of a sentence, so a
 * capitalised one after a full stop is strong evidence that a new sentence has
 * started. Function words and connectives only: a capitalised "Department" or
 * "Smith" proves nothing, because proper nouns are capitalised anywhere.
 */
export const EXCLUSIVE_STARTERS: ReadonlySet<string> = new Set([
  "a", "after", "afterwards", "again", "all", "also", "although", "and", "another",
  "any", "as", "at", "because", "before", "besides", "between", "both", "but",
  "by", "consequently", "during", "each", "either", "even", "every", "finally",
  "first", "for", "from", "furthermore", "he", "hence", "her", "here", "his",
  "how", "however", "if", "in", "instead", "into", "it", "its", "later",
  "likewise", "meanwhile", "moreover", "most", "much", "neither", "nevertheless",
  "next", "no", "none", "nonetheless", "nor", "not", "now", "of", "on", "once",
  "only", "or", "otherwise", "our", "over", "she", "similarly", "since", "so",
  "some", "still", "such", "than", "that", "the", "their", "then", "there",
  "therefore", "these", "they", "this", "those", "though", "thus", "to",
  "under", "unless", "until", "up", "us", "we", "what", "when", "whenever",
  "where", "whereas", "wherever", "whether", "which", "while", "who", "whom",
  "whose", "why", "with", "within", "without", "yet", "you", "your",
]);

/**
 * Formal words with an everyday equivalent. The core skill has always told
 * writers to prefer the plain word, and nothing checked it.
 *
 * Exact words only. A word is reported where it is used, never where it is
 * being discussed, so the skill can name "utilise" as an example without the
 * engine treating that as a lapse.
 */
export const COMPLEX_WORDS: ReadonlyMap<string, string> = new Map([
  ["utilise", "use"],
  ["utilize", "use"],
  ["utilising", "using"],
  ["utilizing", "using"],
  ["commence", "start"],
  ["commences", "starts"],
  ["commenced", "started"],
  ["ascertain", "find"],
  ["facilitate", "help"],
  ["facilitates", "helps"],
  ["endeavour", "try"],
  ["endeavor", "try"],
  ["terminate", "end"],
  ["terminates", "ends"],
  ["aforementioned", "this"],
  ["notwithstanding", "despite"],
  ["henceforth", "now"],
  ["thereafter", "then"],
  ["whereby", "how"],
  ["herein", "here"],
  ["thereof", "its"],
  ["therein", "inside"],
  ["expedite", "hasten"],
  ["disseminate", "share"],
  ["remuneration", "pay"],
]);

/**
 * Openings that say nothing. The core skill's first rule is to begin with the
 * answer, and a filler opening delays it by a whole sentence.
 */
export const FILLER_OPENINGS: readonly string[] = [
  "certainly", "sure", "of course", "absolutely", "great question",
  "good question", "happy to help", "i'd be happy to", "i would be happy to",
  "let me", "as an ai", "here is the summary", "here's the summary",
  "in this document we will", "this document will",
];

/**
 * Double negatives. A reader has to unpick two negations to reach one meaning,
 * which is the part of positive framing a deterministic rule can judge.
 *
 * A blanket check for "do not" and "never" was measured and rejected: it found
 * 58 constructions in this repository's own documents, of which only three
 * were warnings, so the rule would have been noise.
 */
export const DOUBLE_NEGATIVES: readonly string[] = [
  "not unlike", "not uncommon", "not unusual", "not unreasonable",
  "not unimportant", "not insignificant", "not inconsiderable", "not without",
  "never without", "cannot fail to", "not impossible", "not unknown",
  "no fewer than no", "not unhelpful", "not unclear",
];

/**
 * Product names written in lower case. A lower-case word after a full stop
 * usually continues a sentence, and these are the everyday exceptions.
 */
export const LOWERCASE_NAMES: ReadonlySet<string> = new Set([
  "iOS", "iPhone", "iPad", "iPadOS", "macOS", "watchOS", "tvOS", "visionOS",
  "eBay", "iTunes", "iCloud", "eSIM", "npm", "pnpm", "nginx", "ffmpeg",
]);
