
[settings]
experimental = true

[tools]
"cargo:p1rallels/codemapper" = "latest"
"cargo:tgt" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:aristocratos/btop"= "latest"
"github:asciinema/asciinema" = "latest"
"github:cantino/mcfly" = "latest"
"github:d-kuro/gwq" = "latest"
"github:hmarr/codeowners" = "latest"
"github:home-assistant/cli" = "latest"
"github:mfontanini/presenterm" = "latest"
"github:moonrepo/moon" = "latest"
"github:moonrepo/proto" = "latest"
"github:scottmckendry/pokemon-go-colorscripts" = "latest"
"github:terrastruct/d2" = "latest"
"go:github.com/Crosse/font-install" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:oss.terrastruct.com/d2" = "latest"
"npm:@earendil-works/gondolin" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:agent-browser" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:firefox-devtools-mcp" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:gtop" = "latest"
"npm:little-coder" = "1.4.3"
"npm:mcporter" = "latest"
"npm:release-please" = "latest"
"npm:semver" = "latest"
"npm:surf-cli" = "latest"
"npm:typescript-language-server" = "latest"
"pipx:huggingface_hub" = "latest"
"pipx:marker-pdf"= { version = "latest", uvx_args = "--with psutil" }
"pipx:open-webui" = "latest"
"ubi:trufflesecurity/trufflehog" = "latest"
act= "latest"
action-validator = "latest"
actionlint= "latest"
age= "latest"
ansible = { version = "latest", pipx_args = "--include-deps", uvx = "false" }
ast-grep = "latest"
awscli= { version = "latest", symlink_bins = "true" }
bat= "latest"
bats = "latest"
bottom = "latest"
btop = "latest"
bun = "latest"
cloudflared = "latest"
cmake= "latest"
dasel = "latest"
deno= "latest"
dotnet= "latest"
fzf= "latest"
github-cli= "latest"
glow = "latest"
go = "latest"
golang="1.18.3"
golangci-lint = "latest"
grype = "latest"
hk = "latest"
java= "latest"
jq= "latest"
lazygit= "latest"
neovim = "latest"
node = "latest"
npm = "latest"
pipx = "latest"
pitchfork = "latest"
pkl = "latest"
pnpm = "latest"
python = "latest"
ripgrep= "latest"
rust= "latest"
semver = "latest"
shellcheck= "latest"
shfmt= "latest"
starship = "latest"
terraform= "latest"
tombi = "latest"
trufflehog = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
yarn= "latest"
yq = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zellij = "latest"
zig= "latest"
"github:max-sixty/worktrunk" = "latest"
lazydocker = "0.25.2"
"npm:portless" = "latest"
"pipx:basic-memory" = "latest"


[shell_alias]
pi="mise x node@22 -- pi --no-skills"
piupdate="mise x node@22 -- pi update"
piinstall="mise x node@22 -- pi install"
