
[settings]
experimental = true

[tools]
"cargo:p1rallels/codemapper" = "latest"
"cargo:tgt" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:aristocratos/btop"= "latest"
"github:asciinema/asciinema" = "latest"
"github:cantino/mcfly" = "latest"
"github:d-kuro/gwq" = "latest"
"github:hmarr/codeowners" = "latest"
"github:home-assistant/cli" = "latest"
"github:mfontanini/presenterm" = "latest"
"github:moonrepo/moon" = "latest"
"github:moonrepo/proto" = "latest"
"github:scottmckendry/pokemon-go-colorscripts" = "latest"
"github:terrastruct/d2" = "latest"
"github:max-sixty/worktrunk" = "0.52.0"
#"golang:oss.terrastruct.com/d2" = "latest"
"npm:@earendil-works/gondolin" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:agent-browser" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:firefox-devtools-mcp" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:gtop" = "latest"
"npm:mcporter" = "latest"
"npm:release-please" = "latest"
"npm:semver" = "latest"
"npm:surf-cli" = "latest"
"npm:typescript-language-server" = "latest"
"pipx:huggingface_hub" = "latest"
#"pipx:marker-pdf"= { version = "latest", uvx_args = "--with psutil" }
"ubi:trufflesecurity/trufflehog" = "latest"
act= "latest"
action-validator = "latest"
actionlint= "latest"
age= "latest"
ansible = { version = "latest", pipx_args = "--include-deps", uvx = "false" }
ast-grep = "latest"
awscli= { version = "latest", symlink_bins = "true" }
bat= "latest"
bats = "latest"
bottom = "latest"
btop = "latest"
bun = "latest"
cloudflared = "latest"
cmake= "latest"
deno= "latest"
dotnet= "latest"
fzf= "latest"
github-cli= "latest"
glow = "latest"
golang="1.18.3"
grype = "latest"
hk = "latest"
java= "latest"
jq= "latest"
lazygit= "latest"
neovim = "0.11.7"
node = "latest"
npm = "latest"
pipx = "latest"
pitchfork = "latest"
pkl = "latest"
pnpm = "latest"
python = "latest"
ripgrep= "latest"
rust= "latest"
semver = "latest"
shellcheck= "latest"
shfmt= "latest"
starship = "latest"
terraform= "latest"
tombi = "latest"
trufflehog = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
yarn= "latest"
yq = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zellij = "0.44.1"
zig= "latest"
lazydocker = "0.25.2"
pdm = "latest"
"npm:portless" = "latest"
"pipx:basic-memory" = "latest"
"github:ggml-org/llama.cpp" = "b9555"
traefik = "latest"
"npm:neofetch" = "latest"
"npm:kandev" = "latest"
lua = "latest"
"github:finefindus/artem" = "latest"
"npm:takumi-js" = "latest"
"npm:serve" = "latest"
"npm:poster-ai" = "0.5.0"
"npm:@tobilu/qmd" = "latest"
"github:can1357/oh-my-pi" = "latest"

[env]
PI_SUBAGENT_MUX = "zellij"
PI_SUBAGENT_ZELLIJ_PLACEMENT = "right-stack"

[shell_alias]
pi="mise x node@lts -- pi --no-skills"
piupdate="mise x node@lts -- pi update"
piinstall="mise x node@lts -- pi install"
