[bootstrap]
config_roots = ["manifests/common/*", "manifests/unix/*"]

[bootstrap.repos]
"~/.config/nvim" = { url = "git@github.com:zenobi-us/astronvim.profile.git" }

[dotfiles]
"~/.config/mise/config.toml" = { source = "mise.toml", mode = "symlink" }
"~/.config/mise/tasks" = { source = "files/devtools/mise/tasks", mode = "symlink" }

[env]
VISUAL = "nvim"
EDITOR = "nvim"
AGENT_BUNDLE_STORAGE_PATH_PATTERN = "$DOTFILE_REPO_ROOT/files/devtools/agent/bundles/{domain}/"
