monorepo_root = true

[bootstrap]
config_roots = ["files/*/*"]

[bootstrap.repos]
"~/.config/nvim" = { url = "git@github.com:zenobi-us/astronvim.profile.git" }

[env]
VISUAL = "nvim"
EDITOR = "nvim"
AGENT_BUNDLE_STORAGE_PATH_PATTERN = "$DOTFILE_REPO_ROOT/files/devtools/agent/bundles/{domain}/"
