[settings]
experimental = true

[tools]
"github:cantino/mcfly" = "0.9.4"
worktrunk = { version = "0.80.0", workflow = "release.yaml" }
usage = "latest"
starship = "latest"

"act" = "latest"
"action-validator" = "latest"
"actionlint" = "latest"
"age" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"ast-grep" = "latest"
"awscli" = { "version" = "latest", "symlink_bins" = "true" }
"bats" = "latest"
"btop" = "latest"
"bun" = "latest"
"cargo:p1rallels/codemapper" = "latest"
"cargo:rustledger" = "0.21.0"
"claude" = "latest"
"claude-code" = "latest"
"cloudflared" = "latest"
"cmake" = "latest"
"deno" = "latest"
"dotnet" = "latest"
"fd" = "latest"
"fzf" = "latest"
"github-cli" = "latest"
"github:AlexsJones/llmfit" = "latest"
"github:AlexsJones/llmserve" = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:JustVugg/colibri" = "latest"
"github:NVIDIA/OpenShell" = "latest"
"github:afshinm/zerobox" = "0.3.3"
"github:alacritty/alacritty" = "latest"
"github:aristocratos/btop" = "latest"
"github:can1357/oh-my-pi" = "latest"
"github:earendil-works/pi" = "latest"
"github:finefindus/artem" = "latest"
"github:gopasspw/gopass" = "latest"
"github:graykode/abtop" = "latest"
"github:harehare/mq" = "latest"
"github:hmarr/codeowners" = "latest"
"github:jarun/nnn" = "latest"
"github:kurama/dealve-tui" = "latest"
"github:margin-lab/evals" = "latest"
"github:max-sixty/worktrunk" = "0.52.0"
"github:mexirica/aptui" = "latest"
"github:moonrepo/moon" = "latest"
"github:moonrepo/proto" = "latest"
"github:mwunsch/termscope" = "latest"
"github:sockheadrps/llmctl" = "0.2.2"
"github:terrastruct/d2" = "latest"
"github:valentjn/lsp-cli" = "latest"
"github:vercel-labs/agent-browser" = "latest"
"glab" = "latest"
"glow" = "latest"
"go:github.com/Crosse/font-install" = "latest"
"golang" = "1.25.0"
"granted" = "latest"
"grype" = "latest"
"herdr" = "latest"
"hk" = "latest"
"hrdx" = "latest"
"java" = "latest"
"jq" = "latest"
"lazydocker" = "0.25.2"
"lazygit" = "latest"
"lua" = "latest"
"mc" = "latest"
"micro" = "latest"
"neovim" = "latest"
"node" = "22"
"npm" = "latest"
"npm:@earendil-works/gondolin" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@playwright/cli" = "0.1.22"
"npm:agent-browser" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:firefox-devtools-mcp" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:kandev" = "latest"
"npm:mcporter" = "latest"
"npm:neofetch" = "latest"
"npm:portless" = "latest"
"npm:poster-ai" = "0.5.0"
"npm:release-please" = "latest"
"npm:semver" = "latest"
"npm:serve" = "latest"
"npm:surf-cli" = { "version" = "latest", "allow_low_downloads" = true }
"npm:takumi-js" = "latest"
"npm:tempomat" = "latest"
"npm:typescript-language-server" = "latest"
"pdm" = "latest"
"pipx" = "latest"
"pipx:comfy-cli" = "latest"
"pipx:itch-dl" = "latest"
"pitchfork" = "latest"
"pkl" = "latest"
"pnpm" = "latest"
"python" = "latest"
"ripgrep" = "latest"
"rust" = "latest"
"semver" = "latest"
"shellcheck" = "latest"
"shfmt" = "latest"
"terraform" = "latest"
"tombi" = "latest"
"traefik" = "latest"
"trufflehog" = "latest"
"uv" = "0.12.17"
"watchexec" = "latest"
"yarn" = "latest"
"youtube-dl" = "latest"
"yq" = "latest"
"yt-dlp" = { "version" = "latest", "rename_exe" = "yt-dlp" }
"zig" = "latest"
"zot" = "latest"
[dotfiles]
"~/.config/mise/config.toml" = { source = "./mise.toml", mode = "symlink" }
