[bootstrap.repos]
"~/AppData/Local/nvim" = { url = "git@github.com:zenobi-us/astronvim.profile.git" }

[bootstrap.hooks.post-dotfiles]
run = """
powershell.exe -NoProfile -Command "[Environment]::SetEnvironmentVariable('MISE_GLOBAL_CONFIG_ROOT', '{{ config_root }}', 'User')"
"""
