onboarding = false

[theme]

name = "terminal"
auto_switch = false

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false

[keys]
prefix="ctrl+/"

[ui.sidebar.spaces]
rows = [
  ["state_icon", { token = "workspace", bold = true }],
  [
    { token = "branch", dim = true },
    "git_status",
    { token = "$active_tab", dim = true },
  ],
]

#
# Cli: lazygit
# 
[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[ui]

agent_panel_sort = "priority"
prompt_new_tab_name = false
status_indicators = "dots"

