[tools]
"github:terrastruct/d2" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"github:finefindus/artem" = "latest"
"npm:takumi-js" = "latest"
"npm:poster-ai" = "0.5.0"
"pipx:comfy-cli" = "latest"
