[tools]
bun = "latest"
deno = "latest"
dotnet = "latest"
golang = "1.25.0"
java = "latest"
lua = "latest"
node = "22"
npm = "latest"
pdm = "latest"
pipx = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
uv = "0.12.17"
yarn = "latest"
zig = "latest"
pkl = "latest"
