[dotfiles]
"~/.pi/agent/APPEND_SYSTEM.md" = { source = "./agent/APPEND_SYSTEM.md", mode = "symlink" }
"~/.pi/agent/extensions" = { source = "./agent/extensions", mode = "symlink" }
"~/.pi/agent/fzf.json" = { source = "./agent/fzf.json", mode = "symlink" }
"~/.pi/agent/package.json" = { source = "./agent/package.json", mode = "symlink" }
"~/.pi/agent/packages" = { source = "./agent/packages", mode = "symlink" }
"~/.pi/agent/pi-sub-bar-settings.json" = { source = "./agent/pi-sub-bar-settings.json", mode = "symlink" }
"~/.pi/agent/pi-sub-core-settings.json" = { source = "./agent/pi-sub-core-settings.json", mode = "symlink" }
"~/.pi/agent/settings.json" = { source = "./agent/settings.json", mode = "symlink" }
"~/.pi/agent/tsconfig.json" = { source = "./agent/tsconfig.json", mode = "symlink" }
