[tasks."pi.bootstrap"]
description = "Install Zenobius Agent bundle plugins and their dependencies"
tools.bun = "latest"
run = """
bun install
"""
dir = "~/.pi/agent"

[tools]
"github:earendil-works/pi" = "latest"
