modelRoles:
  default: strata/qwen3.8-flash-next-coder-iq1_m:medium
  smol: openai-codex/gpt-6-luna:high
  plan: openai-codex/gpt-6-astra:medium
  commit: openai-codex/gpt-6-luna:off
  slow: strata/qwen3.8-flash-next-coder-iq1_m
symbolPreset: nerd
theme:
  dark: dark-rose-pine
  light: dark-rose-pine
setupVersion: 2
extensions:
  - ~/.omp/agent/hooks/pre
task:
  disabledAgents:
    []
  enableLsp: true
lsp:
  formatOnWrite: true
astGrep:
  enabled: true
github:
  enabled: true
statusLine:
  preset: custom
  separator: none
  sessionAccent: false
  transparent: true
terminal:
  showProgress: true
tui:
  tight: true
display:
  shimmer: kitt
  showTokenUsage: true
  cacheMissMarker: true
recap:
  enabled: false
dev:
  autoqaConsent: granted
composer:
  shape: claude
  tokenRate: true
git:
  enabled: false
skills:
  customDirectories:
    - ~/.pi/agent/bundles/agent-core/skills
    - ~/.pi/agent/bundles/agent-core/skills/documents
    - ~/.pi/agent/bundles/agent-core/skills/skill-development
    - ~/.pi/agent/bundles/agent-core/skills/sop
    - ~/.pi/agent/bundles/creator/skills
    - ~/.pi/agent/bundles/creator/skills/imagegen
    - ~/.pi/agent/bundles/developer/skills
    - ~/.pi/agent/bundles/developer/skills/atlassian
    - ~/.pi/agent/bundles/developer/skills/better-auth
    - ~/.pi/agent/bundles/developer/skills/browsers
    - ~/.pi/agent/bundles/developer/skills/devtools
    - ~/.pi/agent/bundles/developer/skills/game-dev
    - ~/.pi/agent/bundles/developer/skills/game-dev/godot
    - ~/.pi/agent/bundles/developer/skills/git
    - ~/.pi/agent/bundles/developer/skills/shells
    - ~/.pi/agent/bundles/developer/skills/shells/neovim
    - ~/.pi/agent/bundles/developer/skills/uidev
    - ~/.pi/agent/bundles/matt-pocock/skills
    - ~/.pi/agent/bundles/platform/skills/devtools
    - ~/.pi/agent/bundles/platform/skills/devtools/cloudflare
    - ~/.pi/agent/bundles/platform/skills/devtools/mise
    - ~/.pi/agent/bundles/platform/skills/devtools/moonrepo
    - ~/.pi/agent/bundles/platform/skills/devtools/pi-mono
    - ~/.pi/agent/bundles/platform/skills/homeassistant
    - ~/.pi/agent/bundles/researcher/skills
    - ~/.pi/agent/bundles/researcher/skills/devtools
    - ~/.pi/agent/bundles/writing/skills
    - ~/.pi/agent/bundles/writing/skills/business
    - ~/.pi/agent/bundles/writing/skills/fictional
codexResets:
  autoRedeem: "no"