[dotfiles]
"~/.local/state/zot/config.json" = { source = "../../../files/devtools/zot/config.json", mode = "symlink" }
"~/.local/state/zot/themes" = { source = "../../../files/devtools/zot/themes", mode = "symlink" }
"~/.local/state/zot/extensions/creator" = { source = "../../../files/devtools/agent/bundles/creator", mode = "symlink" }
"~/.local/state/zot/extensions/developer" = { source = "../../../files/devtools/agent/bundles/developer", mode = "symlink" }
"~/.local/state/zot/extensions/matt-pocock" = { source = "../../../files/devtools/agent/bundles/matt-pocock", mode = "symlink" }
"~/.local/state/zot/extensions/platform" = { source = "../../../files/devtools/agent/bundles/platform", mode = "symlink" }
"~/.local/state/zot/extensions/private-share" = { source = "../../../files/devtools/agent/bundles/private-share", mode = "symlink" }
"~/.local/state/zot/extensions/researcher" = { source = "../../../files/devtools/agent/bundles/researcher", mode = "symlink" }
"~/.local/state/zot/extensions/vanilla-green" = { source = "../../../files/devtools/agent/bundles/vanilla-green", mode = "symlink" }
"~/.local/state/zot/extensions/writing" = { source = "../../../files/devtools/agent/bundles/writing", mode = "symlink" }
