#!/usr/bin/env bash
HERE=$(dirname $0)

echo "Setting up ZSH from ${HERE}"

chmod +x ${HERE}/setup*

case "$(uname -s)" in

	Darwin)
		echo "Macos"
		cd ~;
		rm ~/.z*
		ln -s ${HERE}/.zshrc ~/
		ln -s ${HERE}/.zprofile ~/
		ln -s ${HERE}/.zshenv ~/

		./setup.osx.sh
	  ;;

	Linux)
		ln -s ${HERE}/.zshrc ~/
		ln -s ${HERE}/.zprofile ~/
		ln -s ${HERE}/.zshenv ~/

		echo "Linux"
		# ./setup.linux.sh
		;;

	CYGWIN*|MINGW32*|MSYS*)
		echo "MS Windows"
		;;

	*)
		echo 'other OS'
		;;

esac

# Operating System            uname -s
# ------------------------------------------------
# Mac OS X                    Darwin
# Cygwin 32-bit (Win-XP)      CYGWIN_NT-5.1
# Cygwin 32-bit (Win-7 32-bit)CYGWIN_NT-6.1
# Cygwin 32-bit (Win-7 64-bit)CYGWIN_NT-6.1-WOW64
# Cygwin 64-bit (Win-7 64-bit)CYGWIN_NT-6.1
# MinGW (Windows 7 32-bit)    MINGW32_NT-6.1
# MinGW (Windows 10 64-bit)   MINGW64_NT-10.0
# Interix (Services for UNIX) Interix
# MSYS                        MSYS_NT-6.1
# Android                     Linux
# coreutils                   Linux
# CentOS                      Linux
# Fedora                      Linux
# Gentoo                      Linux
# Red Hat Linux               Linux
# Linux Mint                  Linux
# openSUSE                    Linux
# Ubuntu                      Linux
# Unity Linux                 Linux
# Manjaro Linux               Linux
# OpenWRT r40420              Linux
# Debian (Linux)              Linux
# Debian (GNU Hurd)           GNU
# Debian (kFreeBSD)           GNU/kFreeBSD
# FreeBSD                     FreeBSD
# NetBSD                      NetBSD
# DragonFlyBSD                DragonFly
# Haiku                       Haiku
# NonStop                     NONSTOP_KERNEL
# QNX                         QNX
# ReliantUNIX                 ReliantUNIX-Y
# SINIX                       SINIX-Y
# Tru64                       OSF1
# Ultrix                      ULTRIX
# IRIX 32 bits                IRIX
# IRIX 64 bits                IRIX64
# MINIX                       Minix
# Solaris                     SunOS
# UWIN (64-bit Windows 7)     UWIN-W7
# SYS$UNIX:SH on OpenVMS      IS/WB
# z/OS USS                    OS/390
# Cray                        sn5176
# (SCO) OpenServer            SCO_SV
# (SCO) System V              SCO_SV
# (SCO) UnixWare              UnixWare
# IBM AIX                     AIX
# IBM i with QSH              OS400
# HP-UX                       HP-UX

# change the shell
chsh -s /bin/zsh
