#!/usr/bin/env bash
function log () {
	echo "[SETUP] $@"
}

#
# Environment Information
#
PLATFORM="$(uname -s)"
log "Platform: ${PLATFORM}"


#
# Establish Absolute Path to dotfile/zsh root
#
RELATIVETHIS=$0
cd "$(dirname "$RELATIVETHIS")"
case $(basename $RELATIVETHIS) in
	..) ABSOLUTETHIS="$(dirname $(pwd))";;
	.)  ABSOLUTETHIS="$(pwd)";;
	*)  ABSOLUTETHIS="$(pwd)/$(basename $RELATIVETHIS)";;
esac
HEREPATH=$(dirname ${ABSOLUTETHIS})
log "HEREPATH: ${HEREPATH}"

. "${HEREPATH}/lib/sh/absolutepath.zsh";
. "${HEREPATH}/lib/zsh/loadparts.zsh";
. "${HEREPATH}/lib/zsh/task.zsh";

chmod +x ${HERE}/setup.d/*

#
# OS Specific Setup
#
case $PLATFORM in

	Darwin)
		. ${HERE}/setup.d/setup.osx.sh
	  ;;

	Linux)
		. ${HERE}/setup.d/setup.linux.sh
		;;

	CYGWIN*|MINGW32*|MSYS*)
		log "NotSupported: ${PLATFORM}"
		;;

	*)
		;;

esac