#!/usr/bin/env bash
absolute_path() {
    cd "$(dirname "$1")"
    case $(basename $1) in
        ..) echo "$(dirname $(pwd))";;
        .)  echo "$(pwd)";;
        *)  echo "$(pwd)/$(basename )";;
    esac
}

log() {
	echo "[SETUP] $@"
}

HERE=$(dirname $(absolute_path ))
PLATFORM="$(uname -s)"

log "Here: ${HERE}"
log "Platform: ${PLATFORM}"

chmod +x ${HERE}/setup*
chmod +x ${HERE}/setup.d/*

case $PLATFORM in

	Darwin)
		. ${HERE}/setup.d/setup.osx.sh
	  ;;

	Linux)
		. ${HERE}/setup.d/setup.linux.sh
		;;

	CYGWIN*|MINGW32*|MSYS*)
		;;

	*)
		;;

esac

. ${HERE}/setup.d/setup.user.zsh
