[dotfiles]
"~/.claude/settings.json" = { source = "../../../files/devtools/claude/settings.json", mode = "symlink" }
"~/.claude/statusline.sh" = { source = "../../../files/devtools/claude/statusline.sh", mode = "symlink" }
"~/.claude/themes/" = { source = "../../../files/devtools/claude/themes/", mode = "symlink-each" }
"~/.claude/output-styles/" = { source = "../../../files/devtools/claude/output-styles/", mode = "symlink-each" }
"~/.claude/CLAUDE.md" = { source = "../../../files/devtools/agent/AGENTS.md", mode = "symlink" }
"~/.claude/agents" = { source = "../../../files/devtools/agent/agents", mode = "symlink" }
"~/.config/mcporter" = { source = "../../../files/devtools/mcporter", mode = "symlink" }
"~/.config/worktrunk" = { source = "../../../files/devtools/worktrunk", mode = "symlink" }
"~/.local/bin/clip-bridge" = { source = "../../../files/devtools/claude/clip-bridge", mode = "symlink" }
"~/.mcporter" = { source = "../../../files/devtools/mcporter", mode = "symlink" }
"~/.pi/agent/AGENTS.md" = { source = "../../../files/devtools/agent/AGENTS.md", mode = "symlink" }
"~/.pi/agent/APPEND_SYSTEM.md" = { source = "../../../files/devtools/pi/agent/APPEND_SYSTEM.md", mode = "symlink" }
"~/.pi/agent/agents" = { source = "../../../files/devtools/agent/agents", mode = "symlink" }
"~/.pi/agent/bun.lock" = { source = "../../../files/devtools/pi/agent/bun.lock", mode = "symlink" }
"~/.pi/agent/bundles" = { source = "../../../files/devtools/agent/bundles", mode = "symlink" }
"~/.pi/agent/extensions" = { source = "../../../files/devtools/pi/agent/extensions", mode = "symlink" }
"~/.pi/agent/fzf.json" = { source = "../../../files/devtools/pi/agent/fzf.json", mode = "symlink" }
"~/.pi/agent/package.json" = { source = "../../../files/devtools/pi/agent/package.json", mode = "symlink" }
"~/.pi/agent/packages" = { source = "../../../files/devtools/pi/agent/packages", mode = "symlink" }
"~/.pi/agent/pi-sub-bar-settings.json" = { source = "../../../files/devtools/pi/agent/pi-sub-bar-settings.json", mode = "symlink" }
"~/.pi/agent/pi-sub-core-settings.json" = { source = "../../../files/devtools/pi/agent/pi-sub-core-settings.json", mode = "symlink" }
"~/.pi/agent/settings.json" = { source = "../../../files/devtools/pi/agent/settings.json", mode = "symlink" }
"~/.pi/agent/tsconfig.json" = { source = "../../../files/devtools/pi/agent/tsconfig.json", mode = "symlink" }
"~/.local/bin/llama-router" = { source = "../../../files/devtools/llama-router/llama-router.sh", mode = "symlink" }
