[tools]
"npm:@playwright/cli" = "0.1.22"
"npm:agent-browser" = "latest"
"github:vercel-labs/agent-browser" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:firefox-devtools-mcp" = "latest"
"npm:surf-cli" = { version = "latest", allow_low_downloads = true }
