#!/usr/bin/env bash
#MISE description="Bootstrap OS-specific tasks"
#MISE env.DEFAULT_OS="{{ os() }}"
#MISE env.DEFAULT_OS_FAMILY="{{ os_family() }}"
#MISE env.DEFAULT_ARCH="{{ arch() }}"

#USAGE flag "--os <os>" help="Override the operating system"
#USAGE flag "--osfamily <osfamily>" help="Override the operating-system family"

set -euo pipefail

os="${usage_os:-$DEFAULT_OS}"
osfamily="${usage_osfamily:-$DEFAULT_OS_FAMILY}"

echo "OS: $os/$osfamily - $DEFAULT_ARCH"

mise run "bootstrap:osfamily_$osfamily"
mise run "bootstrap:os_$os"
mise run '//files/...:bootstrap'

bun install --frozen-lockfile
