#!/usr/bin/env bash
#MISE description "Bootstrap os tasks"

echo "OS: {{ os() }}/{{ os_family() }} - {{ arch() }}"

function does_task_exist() {
  local task_name="$1"

  mise tasks -J | jq -r '.[] | select(.name == "'"$task_name"'") | .name' | grep -q "$task_name"
}

function run_mise_task() {
  if does_task_exist "$1"; then
    mise run "$1"
  else
    echo "No task defined for $1"
  fi
}

env | grep MISE

run_mise_task "bootstrap:{{ os_family() }}"
run_mise_task "bootstrap:{{ os() }}"
