#!/usr/bin/env bash
#MISE description="Bootstrap Linux system"

pwd {{ config_root }}

mise run //files/assets:install-fonts
if command -v xrdb >/dev/null && [ -f "$HOME/.Xresources" ]; then
  xrdb -merge "$HOME/.Xresources"
fi
